const fs = require('fs');

const dataMap = {
  ta: {
    'auto.soil_type_label': 'மண் வகை',
    'auto.irrigation_label': 'நீர்ப்பாசனம்',
    'auto.water_source_label': 'நீர் ஆதாரம்',
    'auto.last_updated_label': 'கடைசியாக புதுப்பிக்கப்பட்டது',
    'auto.agri_intelligence': 'வேளாண் நுண்ணறிவு',
    'auto.what_if_farm': 'மாற்றுத்திறன் பகுப்பாய்வு: {{crop}} பண்ணை, {{village}}',
    'auto.what_if_simulator': 'AI மாற்றுத்திறன் சிமுலேட்டர்',
    'auto.rainfall_label': 'மழைப்பொழிவு',
    'auto.temperature_label': 'வெப்பநிலை',
    'auto.fertilizer_label': 'உரம்',
    'auto.sowing_density_label': 'விதைக்கும் அடர்த்தி',
    'auto.yield_label': 'மகசூல்',
    'auto.revenue_label': 'வருவாய்',
    'auto.risk_level_label': 'அபாய நிலை',
    'auto.ai_confidence_label': 'AI நம்பிக்கை',
    'auto.ai_insight_label': 'AI கணிப்பு',
    'auto.insight_high_risk': '{{village}} இல் உள்ள உங்கள் {{crop}} பண்ணைக்கு நீர்ப்பாசனத்தை அதிகரித்து விதைப்பு அடர்த்தியைக் குறைக்கவும். மகசூல் திறனை மீட்டெடுக்க சமச்சீர் NPK ஐப் பயன்படுத்தவும்.',
    'auto.insight_medium_risk': 'உங்கள் {{area}} ஏக்கர் {{crop}} பண்ணைக்கு நீரின் அளவைக் கண்காணிக்கவும். {{soil}} மண் நிலைமைகளுக்கு ஏற்ப உரத்தை உகந்ததாக்குங்கள்.',
    'auto.insight_low_risk': 'உங்கள் {{village}} பண்ணையில் அதிக மகசூல் பெற சாதகமான சூழ்நிலை உள்ளது. இந்த பருவத்தில் அதிகபட்ச {{crop}} உற்பத்திக்காக தற்போதைய அளவீடுகளைப் பராமரிக்கவும்.',
    'auto.soil_Red_Loam': 'செம்மண்',
    'auto.irrigation_type_drip': 'சொட்டு நீர்',
    'auto.water_source_borewell': 'ஆழ்குழாய் கிணறு',
    'auto.village_melpadi': 'மேல்பாடி',
    'auto.crop_paddy': 'நெல்',
    'auto.risk_low': 'குறைவு',
    'auto.risk_medium': 'நடுத்தரம்',
    'auto.risk_high': 'அதிகம்',
    'auto.t_ha': 'டன்/எக்'
  },
  te: {
    'auto.soil_type_label': 'మట్టి రకం',
    'auto.irrigation_label': 'నీటిపారుదల',
    'auto.water_source_label': 'నీటి మూలం',
    'auto.last_updated_label': 'చివరిగా నవీకరించబడింది',
    'auto.agri_intelligence': 'అగ్రి ఇంటెలిజెన్స్',
    'auto.what_if_farm': 'వాట్-ఇఫ్: {{crop}} పొలం, {{village}}',
    'auto.what_if_simulator': 'AI వాట్-ఇఫ్ సిమ్యులేటర్',
    'auto.rainfall_label': 'వర్షపాతం',
    'auto.temperature_label': 'ఉష్ణోగ్రత',
    'auto.fertilizer_label': 'ఎరువులు',
    'auto.sowing_density_label': 'విత్తే సాంద్రత',
    'auto.yield_label': 'దిగుబడి',
    'auto.revenue_label': 'ఆదాయం',
    'auto.risk_level_label': 'ప్రమాద స్థాయి',
    'auto.ai_confidence_label': 'AI విశ్వాసం',
    'auto.ai_insight_label': 'AI అంతర్దృష్టి',
    'auto.insight_high_risk': '{{village}} లోని మీ {{crop}} పొలానికి నీటిపారుదల పెంచి విత్తే సాంద్రతను తగ్గించండి. దిగుబడి సామర్థ్యాన్ని పునరుద్ధరించడానికి సమతుల్య NPK ని వాడండి.',
    'auto.insight_medium_risk': 'మీ {{area}} ఎకరాల {{crop}} పొలానికి నీటి స్థాయిలను పర్యవేక్షించండి. {{soil}} మట్టి పరిస్థితుల కోసం ఎరువులను ఆప్టిమైజ్ చేయండి.',
    'auto.insight_low_risk': 'మీ {{village}} పొలంలో అధిక దిగుబడికి పరిస్థితులు అనుకూలంగా ఉన్నాయి. ఈ సీజన్‌లో గరిష్ట {{crop}} ఉత్పత్తి కోసం ప్రస్తుత పారామితులను కొనసాగించండి.',
    'auto.soil_Red_Loam': 'ఎర్ర నేల',
    'auto.irrigation_type_drip': 'బిందు సేద్యం',
    'auto.water_source_borewell': 'బోరుబావి',
    'auto.village_melpadi': 'మెల్పాడి',
    'auto.crop_paddy': 'వరి',
    'auto.risk_low': 'తక్కువ',
    'auto.risk_medium': 'మధ్యస్థం',
    'auto.risk_high': 'అధికం',
    'auto.t_ha': 'టి/హెక్టారు'
  },
  kn: {
    'auto.soil_type_label': 'ಮಣ್ಣಿನ ಪ್ರಕಾರ',
    'auto.irrigation_label': 'ನೀರಾವರಿ',
    'auto.water_source_label': 'ನೀರಿನ ಮೂಲ',
    'auto.last_updated_label': 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'auto.agri_intelligence': 'ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ',
    'auto.what_if_farm': 'ವಾಟ್-ಇಫ್: {{crop}} ಕೃಷಿ, {{village}}',
    'auto.what_if_simulator': 'AI ವಾಟ್-ಇಫ್ ಸಿಮ್ಯುಲೇಟರ್',
    'auto.rainfall_label': 'ಮಳೆ ಪ್ರಮಾಣ',
    'auto.temperature_label': 'ತಾಪಮಾನ',
    'auto.fertilizer_label': 'ರಸಗೊಬ್ಬರ',
    'auto.sowing_density_label': 'ಬಿತ್ತನೆ ಸಾಂದ್ರತೆ',
    'auto.yield_label': 'ಇಳುವರಿ',
    'auto.revenue_label': 'ಆದಾಯ',
    'auto.risk_level_label': 'ಅಪಾಯದ ಮಟ್ಟ',
    'auto.ai_confidence_label': 'AI ವಿಶ್ವಾಸ',
    'auto.ai_insight_label': 'AI ಒಳನೋಟ',
    'auto.insight_high_risk': '{{village}} ದಲ್ಲಿರುವ ನಿಮ್ಮ {{crop}} ಜಮೀನಿಗೆ ನೀರಾವರಿಯನ್ನು ಹೆಚ್ಚಿಸಿ ಮತ್ತು ಬಿತ್ತನೆ ಸಾಂದ್ರತೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಿ. ಇಳುವರಿ ಸಾಮರ್ಥ್ಯವನ್ನು ಮರುಪಡೆಯಲು ಸಮತೋಲಿತ NPK ಬಳಸಿ.',
    'auto.insight_medium_risk': 'ನಿಮ್ಮ {{area}} ಎಕರೆ {{crop}} ಜಮೀನಿಗೆ ನೀರಿನ ಮಟ್ಟವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ. {{soil}} ಮಣ್ಣಿನ ಪರಿಸ್ಥಿತಿಗಳಿಗಾಗಿ ರಸಗೊಬ್ಬರವನ್ನು ಅತ್ಯುತ್ತಮವಾಗಿಸಿ.',
    'auto.insight_low_risk': 'ನಿಮ್ಮ {{village}} ಜಮೀನಿನಲ್ಲಿ ಹೆಚ್ಚಿನ ಇಳುವರಿಗೆ ಪರಿಸ್ಥಿತಿಗಳು ಅನುಕೂಲಕರವಾಗಿವೆ. ಈ ಋತುವಿನಲ್ಲಿ ಗರಿಷ್ಠ {{crop}} ಉತ್ಪಾದನೆಗಾಗಿ ಪ್ರಸ್ತುತ ನಿಯತಾಂಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    'auto.soil_Red_Loam': 'ಕೆಂಪು ಮಣ್ಣು',
    'auto.irrigation_type_drip': 'ಹನಿ ನೀರಾವರಿ',
    'auto.water_source_borewell': 'ಕೊಳವೆ ಬಾವಿ',
    'auto.village_melpadi': 'ಮೆಲ್ಪಾಡಿ',
    'auto.crop_paddy': 'ಭತ್ತ',
    'auto.risk_low': 'ಕಡಿಮೆ',
    'auto.risk_medium': 'ಮಧ್ಯಮ',
    'auto.risk_high': 'ಹೆಚ್ಚು',
    'auto.t_ha': 'ಟಿ/ಹೆಕ್ಟೇರ್'
  },
  ml: {
    'auto.soil_type_label': 'മണ്ണിന്റെ തരം',
    'auto.irrigation_label': 'ജലസേചനം',
    'auto.water_source_label': 'ജലസ്രോതസ്സ്',
    'auto.last_updated_label': 'അവസാനം അപ്ഡേറ്റ് ചെയ്തത്',
    'auto.agri_intelligence': 'അഗ്രി ഇന്റലിജൻസ്',
    'auto.what_if_farm': 'വാട്ട്-ഇഫ്: {{crop}} കൃഷിയിടം, {{village}}',
    'auto.what_if_simulator': 'AI വാട്ട്-ഇഫ് സിമുലേറ്റർ',
    'auto.rainfall_label': 'മഴ',
    'auto.temperature_label': 'താപനില',
    'auto.fertilizer_label': 'വളം',
    'auto.sowing_density_label': 'വിതയ്ക്കുന്ന സാന്ദ്രത',
    'auto.yield_label': 'വിളവ്',
    'auto.revenue_label': 'വരുമാനം',
    'auto.risk_level_label': 'അപകടസാധ്യത',
    'auto.ai_confidence_label': 'AI വിശ്വാസം',
    'auto.ai_insight_label': 'AI ഉൾക്കാഴ്ച',
    'auto.insight_high_risk': '{{village}} ലെ നിങ്ങളുടെ {{crop}} പാടത്തിന് ജലസേചനം വർദ്ധിപ്പിക്കുകയും വിതയ്ക്കുന്ന സാന്ദ്രത കുറയ്ക്കുകയും ചെയ്യുക. വിളവ് വീണ്ടെടുക്കാൻ സന്തുലിതമായ NPK പ്രയോഗിക്കുക.',
    'auto.insight_medium_risk': 'നിങ്ങളുടെ {{area}} ഏക്കർ {{crop}} കൃഷിയിടത്തിലെ ജലനിരപ്പ് നിരീക്ഷിക്കുക. {{soil}} മണ്ണിന്റെ അവസ്ഥകൾക്ക് വളപ്രയോഗം ഒപ്റ്റിമൈസ് ചെയ്യുക.',
    'auto.insight_low_risk': 'നിങ്ങളുടെ {{village}} കൃഷിയിടത്തിൽ ഉയർന്ന വിളവിന് അനുകൂല സാഹചര്യങ്ങളുണ്ട്. ഈ സീസണിൽ പരമാവധി {{crop}} ഉത്പാദനത്തിനായി നിലവിലെ പാരാമീറ്ററുകൾ നിലനിർത്തുക.',
    'auto.soil_Red_Loam': 'ചെമ്മണ്ണ്',
    'auto.irrigation_type_drip': 'തുള്ളി നന',
    'auto.water_source_borewell': 'കുഴൽക്കിണർ',
    'auto.village_melpadi': 'മെൽപാഡി',
    'auto.crop_paddy': 'നെല്ല്',
    'auto.risk_low': 'കുറവ്',
    'auto.risk_medium': 'ഇടത്തരം',
    'auto.risk_high': 'ഉയർന്നത്',
    'auto.t_ha': 'ടൺ/ഹെക്ടർ'
  },
  ur: {
    'auto.soil_type_label': 'مٹی کی قسم',
    'auto.irrigation_label': 'آبپاشی',
    'auto.water_source_label': 'پانی کا ذریعہ',
    'auto.last_updated_label': 'آخری بار اپ ڈیٹ کیا گیا',
    'auto.agri_intelligence': 'ایگری انٹیلیجنس',
    'auto.what_if_farm': 'کیا-اگر: {{crop}} فارم، {{village}}',
    'auto.what_if_simulator': 'AI کیا-اگر سمیلیٹر',
    'auto.rainfall_label': 'بارش',
    'auto.temperature_label': 'درجہ حرارت',
    'auto.fertilizer_label': 'کھاد',
    'auto.sowing_density_label': 'بوائی کی کثافت',
    'auto.yield_label': 'پیداوار',
    'auto.revenue_label': 'آمدنی',
    'auto.risk_level_label': 'خطرے کی سطح',
    'auto.ai_confidence_label': 'AI اعتماد',
    'auto.ai_insight_label': 'AI بصیرت',
    'auto.insight_high_risk': '{{village}} میں اپنے {{crop}} پلاٹ کے لیے آبپاشی میں اضافہ کریں اور بوائی کی کثافت کم کریں۔ پیداوار کی صلاحیت کو بحال کرنے کے لیے متوازن NPK کا اطلاق کریں۔',
    'auto.insight_medium_risk': 'اپنے {{area}} ایکڑ {{crop}} فارم کے لیے پانی کی سطح کی نگرانی کریں۔ {{soil}} مٹی کے حالات کے لیے کھاد کو بہتر بنائیں۔',
    'auto.insight_low_risk': 'آپ کے {{village}} فارم پر زیادہ پیداوار کے لیے حالات سازگار ہیں۔ اس سیزن میں زیادہ سے زیادہ {{crop}} پیداوار کے لیے موجودہ پیرامیٹرز کو برقرار رکھیں۔',
    'auto.soil_Red_Loam': 'سرخ مٹی',
    'auto.irrigation_type_drip': 'ڈرپ',
    'auto.water_source_borewell': 'بورویل',
    'auto.village_melpadi': 'میلپاڈی',
    'auto.crop_paddy': 'دھان',
    'auto.risk_low': 'کم',
    'auto.risk_medium': 'درمیانہ',
    'auto.risk_high': 'زیادہ',
    'auto.t_ha': 'ٹن/ہیکٹر'
  }
};

Object.entries(dataMap).forEach(([lang, map]) => {
  const p = './src/locales/' + lang + '.json';
  if (fs.existsSync(p)) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data.auto) data.auto = {};
    Object.entries(map).forEach(([k, v]) => {
      data.auto[k.replace('auto.', '')] = v;
    });
    fs.writeFileSync(p, JSON.stringify(data, null, 4));
    console.log('Updated ' + lang + '.json with GovDashboard strings');
  }
});
