const fs = require('fs');

const dataMap = {
  ta: {
    title: 'முன்கணிப்பு பார்வை',
    twin_engine: 'இரட்டை இயந்திரம்',
    overall: 'ஒட்டுமொத்த',
    high_rain_days: 'அதிக மழை நாட்கள்',
    high_pest_days: 'அதிக பூச்சி நாட்கள்',
    today: 'இன்று',
    tomorrow: 'நாளை',
    tomorrow_short: 'நாளை',
    generating: 'பார்வையை உருவாக்குகிறது...',
    rain_risk: 'மழை அபாயம்',
    mm_est: 'மிமீ (மதிப்பீடு)',
    pest_risk: 'பூச்சி அபாயம்',
    spray_advised: 'தெளிக்க அறிவுறுத்தப்பட்டுள்ளது',
    monitor_daily: 'தினசரி கண்காணிக்கவும்',
    water_stress: 'நீர் அழுத்தம்',
    yield_trend: 'மகசூல் போக்கு',
    vs_today: 'இன்றுடன் ஒப்பிடுகையில்',
    weekly_yield_trend: 'வாராந்திர மகசூல் போக்கு',
    day_7: '7வது நாள்',
    adv_heavy_rain: '🌧️ பலத்த மழை பெய்ய வாய்ப்புள்ளது — வடிகால் வசதியை சரிசெய்யவும், உரம் இடுவதை தள்ளி வைக்கவும்.',
    adv_high_pest: '🐛 அதிக பூச்சி அழுத்தம் — பயிரை ஆய்வு செய்யவும், வரம்பை மீறினால் தெளிக்கவும்.',
    adv_severe_stress: '💧 கடுமையான நீர் அழுத்தம் — உடனடியாக நீர்ப்பாசனம் செய்யவும்.',
    adv_heat_stress: '🌡️ வெப்ப அழுத்த எச்சரிக்கை — நிழல் வலைகள் பரிந்துரைக்கப்படுகின்றன.',
    adv_moderate_stress: '💧 மிதமான அழுத்தம் — நீர்ப்பாசன அதிர்வெண்ணை அதிகரிக்கவும்.',
    adv_favorable: '✅ நிலைமைகள் சாதகமாக உள்ளன — தற்போதைய அட்டவணையை பராமரிக்கவும்.',
    weather_fair: 'தெளிவு',
    weather_rain: 'மழை',
    weather_clds: 'மேகம்',
    risk_low: 'குறைவு',
    risk_medium: 'நடுத்தரம்',
    risk_high: 'அதிகம்'
  },
  te: {
    title: 'ప్రిడిక్టివ్ ఔట్లుక్',
    twin_engine: 'ట్విన్ ఇంజిన్',
    overall: 'మొత్తం',
    high_rain_days: 'అధిక వర్షపు రోజులు',
    high_pest_days: 'అధిక తెగుళ్ళ రోజులు',
    today: 'ఈరోజు',
    tomorrow: 'రేపు',
    tomorrow_short: 'రేపు',
    generating: 'ఔట్లుక్ రూపొందిస్తోంది...',
    rain_risk: 'వర్షం ప్రమాదం',
    mm_est: 'మి.మీ (అంచనా)',
    pest_risk: 'తెగులు ప్రమాదం',
    spray_advised: 'స్ప్రే చేయాలని సూచించబడింది',
    monitor_daily: 'రోజూ పర్యవేక్షించండి',
    water_stress: 'నీటి ఒత్తిడి',
    yield_trend: 'దిగుబడి ధోరణి',
    vs_today: 'ఈ రోజుతో పోలిస్తే',
    weekly_yield_trend: 'వారపు దిగుబడి ధోరణి',
    day_7: '7వ రోజు',
    adv_heavy_rain: '🌧️ భారీ వర్షం పడే అవకాశం ఉంది — డ్రైనేజీని క్లియర్ చేయండి, ఎరువులు వాయిదా వేయండి.',
    adv_high_pest: '🐛 అధిక తెగులు ఒత్తిడి — పంటను తనిఖీ చేయండి, పరిమితి దాటితే పిచికారీ చేయండి.',
    adv_severe_stress: '💧 తీవ్రమైన నీటి ఒత్తిడి — వెంటనే నీరు పెట్టండి.',
    adv_heat_stress: '🌡️ ఉష్ణ ఒత్తిడి హెచ్చరిక — షేడ్ నెట్స్ సిఫార్సు చేయబడ్డాయి.',
    adv_moderate_stress: '💧 మితమైన ఒత్తిడి — నీటిపారుదల ఫ్రీక్వెన్సీని పెంచండి.',
    adv_favorable: '✅ పరిస్థితులు అనుకూలంగా ఉన్నాయి — ప్రస్తుత షెడ్యూల్‌ని కొనసాగించండి.',
    weather_fair: 'స్పష్టమైన',
    weather_rain: 'వర్షం',
    weather_clds: 'మేఘాలు',
    risk_low: 'తక్కువ',
    risk_medium: 'మధ్యస్థం',
    risk_high: 'అధికం'
  },
  kn: {
    title: 'ಮುನ್ಸೂಚಕ ಮುನ್ನೋಟ',
    twin_engine: 'ಟ್ವಿನ್ ಎಂಜಿನ್',
    overall: 'ಒಟ್ಟಾರೆ',
    high_rain_days: 'ಹೆಚ್ಚು ಮಳೆಯ ದಿನಗಳು',
    high_pest_days: 'ಹೆಚ್ಚು ಕೀಟಗಳ ದಿನಗಳು',
    today: 'ಇಂದು',
    tomorrow: 'ನಾಳೆ',
    tomorrow_short: 'ನಾಳೆ',
    generating: 'ಮುನ್ನೋಟವನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    rain_risk: 'ಮಳೆ ಅಪಾಯ',
    mm_est: 'ಮಿ.ಮೀ (ಅಂದಾಜು)',
    pest_risk: 'ಕೀಟ ಅಪಾಯ',
    spray_advised: 'ಸಿಂಪಡಿಸಲು ಸಲಹೆ ನೀಡಲಾಗಿದೆ',
    monitor_daily: 'ಪ್ರತಿದಿನ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ',
    water_stress: 'ನೀರಿನ ಒತ್ತಡ',
    yield_trend: 'ಇಳುವರಿ ಪ್ರವೃತ್ತಿ',
    vs_today: 'ಇಂದಿನ ಹೋಲಿಕೆಯಲ್ಲಿ',
    weekly_yield_trend: 'ಸಾಪ್ತಾಹಿಕ ಇಳುವರಿ ಪ್ರವೃತ್ತಿ',
    day_7: '7ನೇ ದಿನ',
    adv_heavy_rain: '🌧️ ಭಾರಿ ಮಳೆಯಾಗುವ ಸಾಧ್ಯತೆ ಇದೆ — ಒಳಚರಂಡಿ ತೆರವುಗೊಳಿಸಿ, ರಸಗೊಬ್ಬರ ಮುಂದೂಡಿ.',
    adv_high_pest: '🐛 ಹೆಚ್ಚಿನ ಕೀಟಗಳ ಒತ್ತಡ — ಬೆಳೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ, ಮಿತಿ ಮೀರಿದರೆ ಸಿಂಪಡಿಸಿ.',
    adv_severe_stress: '💧 ತೀವ್ರ ನೀರಿನ ಒತ್ತಡ — ತಕ್ಷಣ ನೀರು ಹಾಯಿಸಿ.',
    adv_heat_stress: '🌡️ ಶಾಖದ ಒತ್ತಡದ ಎಚ್ಚರಿಕೆ — ನೆರಳು ಪರದೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.',
    adv_moderate_stress: '💧 ಮಧ್ಯಮ ಒತ್ತಡ — ನೀರಾವರಿ ಆವರ್ತನವನ್ನು ಹೆಚ್ಚಿಸಿ.',
    adv_favorable: '✅ ಪರಿಸ್ಥಿತಿಗಳು ಅನುಕೂಲಕರವಾಗಿವೆ — ಪ್ರಸ್ತುತ ವೇಳಾಪಟ್ಟಿಯನ್ನು ನಿರ್ವಹಿಸಿ.',
    weather_fair: 'ಸ್ಪಷ್ಟ',
    weather_rain: 'ಮಳೆ',
    weather_clds: 'ಮೋಡ',
    risk_low: 'ಕಡಿಮೆ',
    risk_medium: 'ಮಧ್ಯಮ',
    risk_high: 'ಹೆಚ್ಚು'
  },
  ml: {
    title: 'പ്രവചനാത്മക വീക്ഷണം',
    twin_engine: 'ട്വിൻ എഞ്ചിൻ',
    overall: 'മൊത്തത്തിലുള്ള',
    high_rain_days: 'ഉയർന്ന മഴയുള്ള ദിവസങ്ങൾ',
    high_pest_days: 'ഉയർന്ന കീട ദിവസങ്ങൾ',
    today: 'ഇന്ന്',
    tomorrow: 'നാളെ',
    tomorrow_short: 'നാളെ',
    generating: 'വീക്ഷണം സൃഷ്ടിക്കുന്നു...',
    rain_risk: 'മഴ സാധ്യത',
    mm_est: 'മില്ലീമീറ്റർ (കണക്കാക്കിയ)',
    pest_risk: 'കീട സാധ്യത',
    spray_advised: 'സ്പ്രേ ചെയ്യാൻ നിർദ്ദേശിക്കുന്നു',
    monitor_daily: 'ദിവസവും നിരീക്ഷിക്കുക',
    water_stress: 'ജല സമ്മർദ്ദം',
    yield_trend: 'വിളവ് പ്രവണത',
    vs_today: 'ഇന്നുമായി താരതമ്യം ചെയ്യുമ്പോൾ',
    weekly_yield_trend: 'പ്രതിവാര വിളവ് പ്രവണത',
    day_7: 'ഏഴാം ദിവസം',
    adv_heavy_rain: '🌧️ ശക്തമായ മഴയ്ക്ക് സാധ്യത — ഡ്രെയിനേജ് വൃത്തിയാക്കുക, വളപ്രയോഗം മാറ്റിവെക്കുക.',
    adv_high_pest: '🐛 ഉയർന്ന കീടശല്യം — വിള പരിശോധിക്കുക, പരിധി കവിഞ്ഞാൽ സ്പ്രേ ചെയ്യുക.',
    adv_severe_stress: '💧 കടുത്ത ജല സമ്മർദ്ദം — ഉടൻ നനയ്ക്കുക.',
    adv_heat_stress: '🌡️ ചൂട് മുന്നറിയിപ്പ് — തണൽ വലകൾ ശുപാർശ ചെയ്യുന്നു.',
    adv_moderate_stress: '💧 മിതമായ സമ്മർദ്ദം — ജലസേചന ആവൃത്തി വർദ്ധിപ്പിക്കുക.',
    adv_favorable: '✅ അനുകൂലമായ സാഹചര്യങ്ങൾ — നിലവിലെ ഷെഡ്യൂൾ തുടരുക.',
    weather_fair: 'വ്യക്തമായ',
    weather_rain: 'മഴ',
    weather_clds: 'മേഘം',
    risk_low: 'കുറവ്',
    risk_medium: 'ഇടത്തരം',
    risk_high: 'ഉയർന്നത്'
  },
  ur: {
    title: 'پیشن گوئی کا نقطہ نظر',
    twin_engine: 'ٹوئن انجن',
    overall: 'مجموعی طور پر',
    high_rain_days: 'زیادہ بارش کے دن',
    high_pest_days: 'زیادہ کیڑوں کے دن',
    today: 'آج',
    tomorrow: 'کل',
    tomorrow_short: 'کل',
    generating: 'نقطہ نظر تیار کیا جا رہا ہے...',
    rain_risk: 'بارش کا خطرہ',
    mm_est: 'ملی میٹر (تخمینہ)',
    pest_risk: 'کیڑوں کا خطرہ',
    spray_advised: 'سپرے کا مشورہ دیا گیا',
    monitor_daily: 'روزانہ نگرانی کریں',
    water_stress: 'پانی کی کمی',
    yield_trend: 'پیداوار کا رجحان',
    vs_today: 'آج کے مقابلے میں',
    weekly_yield_trend: 'ہفتہ وار پیداوار کا رجحان',
    day_7: 'ساتواں دن',
    adv_heavy_rain: '🌧️ تیز بارش کا امکان — نکاسی آب صاف کریں، کھاد ڈالنے کو ملتوی کریں۔',
    adv_high_pest: '🐛 کیڑوں کا زیادہ دباؤ — فصل کا معائنہ کریں، حد سے تجاوز کرنے پر سپرے کریں۔',
    adv_severe_stress: '💧 پانی کی شدید کمی — فوری طور پر آبپاشی کریں۔',
    adv_heat_stress: '🌡️ گرمی کے دباؤ کا الرٹ — شیڈ نیٹ کی سفارش کی جاتی ہے۔',
    adv_moderate_stress: '💧 درمیانہ دباؤ — آبپاشی کی فریکوئنسی بڑھائیں۔',
    adv_favorable: '✅ حالات سازگار ہیں — موجودہ شیڈول کو برقرار رکھیں۔',
    weather_fair: 'صاف',
    weather_rain: 'بارش',
    weather_clds: 'بادل',
    risk_low: 'کم',
    risk_medium: 'درمیانہ',
    risk_high: 'زیادہ'
  }
};

Object.entries(dataMap).forEach(([lang, map]) => {
  const p = './src/locales/' + lang + '.json';
  if (fs.existsSync(p)) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data.predictive_outlook) data.predictive_outlook = {};
    Object.entries(map).forEach(([k, v]) => {
      data.predictive_outlook[k] = v;
    });
    fs.writeFileSync(p, JSON.stringify(data, null, 4));
    console.log('Updated ' + lang + '.json with Predictive Outlook strings');
  }
});
