const fs = require('fs');

const translations = {
  te: {
    'district_vellore': 'వెల్లూరు',
    'district_thanjavur': 'తంజావూరు',
    'district_coimbatore': 'కోయంబత్తూరు',
    'district_madurai': 'మధురై',
    'district_salem': 'సేలం',
    'crop_paddy': 'వరి',
    'crop_rice': 'బియ్యం',
    'crop_cotton': 'పత్తి',
    'crop_groundnut': 'వేరుశెనగ',
    'crop_maize': 'మొక్కజొన్న',
    'health_warning': 'హెచ్చరిక',
    'health_good': 'మంచిది',
    'health_critical': 'క్లిష్టమైనది',
    'health_excellent': 'అద్భుతమైన',
    'risk_low': 'తక్కువ',
    'risk_medium': 'మధ్యస్థం',
    'risk_high': 'ఎక్కువ',
    'risk_critical': 'అత్యంత ప్రమాదకరం',
    'name_Muthu_Selvam': 'ముత్తు సెల్వం',
    'name_Kamala_Devi': 'కమలా దేవి',
    'name_Rajan_Kumar': 'రాజన్ కుమార్',
    'name_Priya_Nair': 'ప్రియా నాయర్',
    'name_Suresh_Babu': 'సురేష్ బాబు',
    'unit_t': 'టన్నులు',
    'unit_kg': 'కిలోలు',
    'apply_urea': 'నత్రజని లోపాన్ని నివారించడానికి ఎకరానికి 25 కిలోల యూరియాను వేయండి.',
    'apply_dap': 'భాస్వరం లోపాన్ని నివారించడానికి ఎకరానికి 50 కిలోల DAP ని వేయండి.',
    'apply_mop': 'పొటాషియం లోపాన్ని నివారించడానికి ఎకరానికి 30 కిలోల MOP ని వేయండి.',
    'increase_irrigation': 'నీటిపారుదలని పెంచండి. బిందు సేద్యం (drip) ఉపయోగించండి.',
    'pest_control': 'తెగులు పర్యవేక్షణ పెంచండి. IPM-సిఫార్సు చేసిన మందులు వాడండి.',
    'crop_review': 'పంట నిర్వహణ విధానాలను సమీక్షించి స్థానిక వ్యవసాయ నిపుణుడిని సంప్రదించండి.',
    'maintain': 'అన్ని పారామితులు అనుకూలమైనవి. ప్రస్తుత వ్యవసాయ పద్ధతులను కొనసాగించండి.'
  },
  kn: {
    'district_vellore': 'ವೆಲ್ಲೂರು',
    'district_thanjavur': 'ತಂಜಾವೂರು',
    'district_coimbatore': 'ಕೊಯಮತ್ತೂರು',
    'district_madurai': 'ಮಧುರೈ',
    'district_salem': 'ಸೇಲಂ',
    'crop_paddy': 'ಭತ್ತ',
    'crop_rice': 'ಅಕ್ಕಿ',
    'crop_cotton': 'ಹತ್ತಿ',
    'crop_groundnut': 'ಕಡಲೆಕಾಯಿ',
    'crop_maize': 'ಮೆಕ್ಕೆಜೋಳ',
    'health_warning': 'ಎಚ್ಚರಿಕೆ',
    'health_good': 'ಉತ್ತಮ',
    'health_critical': 'ನಿರ್ಣಾಯಕ',
    'health_excellent': 'ಅತ್ಯುತ್ತಮ',
    'risk_low': 'ಕಡಿಮೆ',
    'risk_medium': 'ಮಧ್ಯಮ',
    'risk_high': 'ಹೆಚ್ಚು',
    'risk_critical': 'ಅತ್ಯಂತ ಅಪಾಯಕಾರಿ',
    'name_Muthu_Selvam': 'ಮುತ್ತು ಸೆಲ್ವಂ',
    'name_Kamala_Devi': 'ಕಮಲಾ ದೇವಿ',
    'name_Rajan_Kumar': 'ರಾಜನ್ ಕುಮಾರ್',
    'name_Priya_Nair': 'ಪ್ರಿಯಾ ನಾಯರ್',
    'name_Suresh_Babu': 'ಸುರೇಶ್ ಬಾಬು',
    'unit_t': 'ಟನ್',
    'unit_kg': 'ಕೆ.ಜಿ',
    'apply_urea': 'ಸಾರಜನಕ ಕೊರತೆಯನ್ನು ನಿವಾರಿಸಲು ಎಕರೆಗೆ 25 ಕೆ.ಜಿ ಯೂರಿಯಾ ಬಳಸಿ.',
    'apply_dap': 'ರಂಜಕ ಕೊರತೆಯನ್ನು ನಿವಾರಿಸಲು ಎಕರೆಗೆ 50 ಕೆ.ಜಿ DAP ಬಳಸಿ.',
    'apply_mop': 'ಪೊಟ್ಯಾಸಿಯಮ್ ಕೊರತೆಯನ್ನು ನಿವಾರಿಸಲು ಎಕರೆಗೆ 30 ಕೆ.ಜಿ MOP ಬಳಸಿ.',
    'increase_irrigation': 'ನೀರಾವರಿಯನ್ನು ಹೆಚ್ಚಿಸಿ. ಹನಿ ನೀರಾವರಿ ಬಳಸಿ.',
    'pest_control': 'ಕೀಟಗಳ ಮೇಲ್ವಿಚಾರಣೆಯನ್ನು ಹೆಚ್ಚಿಸಿ. IPM ಶಿಫಾರಸು ಮಾಡಿದ ಕೀಟನಾಶಕಗಳನ್ನು ಬಳಸಿ.',
    'crop_review': 'ಬೆಳೆ ನಿರ್ವಹಣಾ ಅಭ್ಯಾಸಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸ್ಥಳೀಯ ಕೃಷಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    'maintain': 'ಎಲ್ಲಾ ನಿಯತಾಂಕಗಳು ಸೂಕ್ತವಾಗಿವೆ. ಪ್ರಸ್ತುತ ಕೃಷಿ ಪದ್ಧತಿಗಳನ್ನು ಮುಂದುವರಿಸಿ.'
  },
  ml: {
    'district_vellore': 'വെല്ലൂർ',
    'district_thanjavur': 'തഞ്ചാവൂർ',
    'district_coimbatore': 'കോയമ്പത്തൂർ',
    'district_madurai': 'മധുര',
    'district_salem': 'സേലം',
    'crop_paddy': 'നെല്ല്',
    'crop_rice': 'അരി',
    'crop_cotton': 'പരുത്തി',
    'crop_groundnut': 'നിലക്കടല',
    'crop_maize': 'ചോളം',
    'health_warning': 'മുന്നറിയിപ്പ്',
    'health_good': 'നല്ലത്',
    'health_critical': 'ഗുരുതരം',
    'health_excellent': 'മികച്ചത്',
    'risk_low': 'കുറവ്',
    'risk_medium': 'ഇടത്തരം',
    'risk_high': 'കൂടുതൽ',
    'risk_critical': 'വളരെ ഗുരുതരം',
    'name_Muthu_Selvam': 'മുത്തു ശെൽവം',
    'name_Kamala_Devi': 'കമലാ ദേവി',
    'name_Rajan_Kumar': 'രാജൻ കുമാർ',
    'name_Priya_Nair': 'പ്രിയ നായർ',
    'name_Suresh_Babu': 'സുരേഷ് ബാബു',
    'unit_t': 'ടൺ',
    'unit_kg': 'കി.ഗ്രാം',
    'apply_urea': 'നൈട്രജൻ കുറവ് പരിഹരിക്കാൻ ഏക്കറിന് 25 കിലോ യൂറിയ പ്രയോഗിക്കുക.',
    'apply_dap': 'ഫോസ്ഫറസ് കുറവ് പരിഹരിക്കാൻ ഏക്കറിന് 50 കിലോ DAP പ്രയോഗിക്കുക.',
    'apply_mop': 'പൊട്ടാസ്യം കുറവ് പരിഹരിക്കാൻ ഏക്കറിന് 30 കിലോ MOP പ്രയോഗിക്കുക.',
    'increase_irrigation': 'ജലസേചനം കൂട്ടുക. തുള്ളിനന (drip) പരിഗണിക്കുക.',
    'pest_control': 'കീട നിരീക്ഷണം വർദ്ധിപ്പിക്കുക. IPM ശുപാർശ ചെയ്യുന്ന കീടനാശിനികൾ ഉപയോഗിക്കുക.',
    'crop_review': 'വിള പരിപാലന രീതികൾ അവലോകനം ചെയ്യുക, പ്രാദേശിക കാർഷിക വിദഗ്ദ്ധനെ സമീപിക്കുക.',
    'maintain': 'എല്ലാ പാരാമീറ്ററുകളും അനുകൂലമാണ്. നിലവിലെ കൃഷിരീതികൾ തുടരുക.'
  },
  ur: {
    'district_vellore': 'ویلور',
    'district_thanjavur': 'تنجاور',
    'district_coimbatore': 'کوئمبتور',
    'district_madurai': 'مدورئی',
    'district_salem': 'سیلم',
    'crop_paddy': 'دھان',
    'crop_rice': 'چاول',
    'crop_cotton': 'کپاس',
    'crop_groundnut': 'مونگ پھلی',
    'crop_maize': 'مکئی',
    'health_warning': 'انتباہ',
    'health_good': 'اچھا',
    'health_critical': 'نازک',
    'health_excellent': 'بہترین',
    'risk_low': 'کم',
    'risk_medium': 'درمیانہ',
    'risk_high': 'زیادہ',
    'risk_critical': 'انتہائی خطرناک',
    'name_Muthu_Selvam': 'متھو سیلوم',
    'name_Kamala_Devi': 'کملا دیوی',
    'name_Rajan_Kumar': 'راجن کمار',
    'name_Priya_Nair': 'پریا نائر',
    'name_Suresh_Babu': 'سریش بابو',
    'unit_t': 'ٹن',
    'unit_kg': 'کلوگرام',
    'apply_urea': 'نائٹروجن کی کمی کو پورا کرنے کے لئے 25 کلوگرام / ایکڑ یوریا کا استعمال کریں۔',
    'apply_dap': 'فاسفورس کی کمی کو پورا کرنے کے لئے 50 کلوگرام / ایکڑ DAP کا استعمال کریں۔',
    'apply_mop': 'پوٹاشیم کی کمی کو پورا کرنے کے لئے 30 کلوگرام / ایکڑ MOP کا استعمال کریں۔',
    'increase_irrigation': 'آبپاشی میں اضافہ کریں۔ ڈرپ اریگیشن کا استعمال کریں۔',
    'pest_control': 'کیڑوں کی نگرانی میں اضافہ کریں۔ IPM کی تجویز کردہ کیڑے مار ادویات استعمال کریں۔',
    'crop_review': 'فصل کے انتظام کے طریقوں کا جائزہ لیں اور مقامی زرعی ماہر سے مشورہ کریں۔',
    'maintain': 'تمام پیرامیٹرز بہترین ہیں۔ موجودہ کاشتکاری کے طریقوں کو برقرار رکھیں۔'
  }
};

Object.entries(translations).forEach(([lang, map]) => {
  const p = './src/locales/' + lang + '.json';
  if (fs.existsSync(p)) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data.auto) data.auto = {};
    Object.entries(map).forEach(([k, v]) => {
      data.auto[k] = v;
    });
    fs.writeFileSync(p, JSON.stringify(data, null, 4));
    console.log('Updated ' + lang + '.json with dynamic translations');
  }
});
