const fs = require('fs');

const engineTranslations = {
  ta: {
    'engine.syn_high': 'அதிக',
    'engine.syn_medium': 'நடுத்தர',
    'engine.syn_low': 'குறைந்த',
    'engine.rd_shallow': 'ஆழமற்ற',
    'engine.rd_medium': 'நடுத்தர',
    'engine.rd_deep': 'ஆழமான',
    'engine.crop_blackgram': 'உளுந்து',
    'engine.crop_greengram': 'பச்சைப்பயிறு',
    'engine.crop_sesbania': 'செஸ்பேனியா',
    'engine.crop_cowpea': 'தட்டைப்பயிறு',
    'engine.crop_onion': 'வெங்காயம்',
    'engine.crop_coriander': 'கொத்தமல்லி',
    'engine.crop_redgram': 'துவரை',
    'engine.crop_castor': 'ஆமணக்கு',
    'engine.crop_sunflower': 'சூரியகாந்தி',
    'engine.crop_pumpkin': 'பூசணி',
    'engine.comp_paddy_blackgram': 'வரப்புகளில் நைட்ரஜனை நிலைநிறுத்துகிறது, நின்ற நீருக்காக போட்டியிடாமல் எஞ்சிய ஈரப்பதத்தில் வளரும்',
    'engine.comp_paddy_greengram': 'வயல் விளிம்புகள் மற்றும் அறுவடைக்கு பிந்தைய மண்ணின் ஈரப்பதத்தைப் பயன்படுத்தும் குறுகிய கால பயிர்',
    'engine.comp_paddy_sesbania': 'மண் வளத்தை மேம்படுத்தும் மற்றும் நீர் தேங்கிய நிலைகளைத் தாங்கும் பசுந்தாள் உரப் பயிர்',
    'engine.comp_cotton_blackgram': 'ஆழமான வேர்கள் கொண்ட பருத்தியுடன் போட்டியிடாமல் மேலோட்டமான வேர்கள் நீரை உறிஞ்சும்',
    'engine.comp_cotton_greengram': 'விரைவாக வளரும் பயிர் பருத்தி வரிசைகளுக்கு இடையில் பொருந்தி நைட்ரஜனை சரிசெய்கிறது',
    'engine.comp_cotton_cowpea': 'வறட்சியைத் தாங்கும் மற்றும் பருத்தி வரிசைகளுக்கு இடையில் மண் அமைப்பை மேம்படுத்துகிறது',
    'engine.comp_sugar_onion': 'கரும்பு முழுமையாக வளருவதற்கு முன் அகலமான வரிசை இடைவெளியைப் பயன்படுத்திக் கொள்கிறது',
    'engine.comp_sugar_coriander': 'கரும்பு வளரும் ஆரம்ப கட்டத்தில் குறுகிய கால வருமானம் தரும் பயிர்',
    'engine.comp_sugar_blackgram': 'நீண்ட கரும்பு வளர்ச்சி சுழற்சியின் போது மண்ணில் நைட்ரஜனை செறிவூட்டுகிறது',
    'engine.comp_ground_redgram': 'ஆழமான வேர்கள் அடிமண் ஈரப்பதத்தை உறிஞ்சுகின்றன, இது நிலக்கடலையின் மேலோட்டமான வேர்களுக்கு পরিপূரணமாகும்',
    'engine.comp_ground_castor': 'வறட்சியைத் தாங்கும் எல்லைப் பயிர், காற்றின் தாக்கத்தையும் நிலக்கடலைக்கான நீர் இழப்பையும் குறைக்கிறது',
    'engine.comp_ground_sunflower': 'திறமையான நிலப் பயன்பாட்டுப் பயிர், நிலக்கடலையைப் போன்ற பாசன முறைகளைத் தாங்கக்கூடியது',
    'engine.comp_maize_cowpea': 'மக்காச்சோளத்திற்கு நைட்ரஜனை சரிசெய்கிறது மற்றும் ஆவியாவதைக் குறைக்கும் நிலக்கவர் வழங்குகிறது',
    'engine.comp_maize_blackgram': 'மேலோட்டமான வேர்களைக் கொண்ட பயிர் மக்காச்சோள வரிசைகளுக்கு இடையில் ஆழமான ஈரப்பதத்திற்கு போட்டியிடாமல் பொருந்துகிறது',
    'engine.comp_maize_pumpkin': 'படரும் கொடி களைகளைக் கட்டுப்படுத்துகிறது மற்றும் மக்காச்சோள விதானத்தின் கீழ் மண்ணின் ஈரப்பதத்தைப் பாதுகாக்கிறது',
    'engine.comp_def_blackgram': 'பெரும்பாலான பாசன முறைகளுக்கு ஏற்ற பொதுவான ஊடுபயிர்',
    'engine.comp_def_greengram': 'குறைந்த நீர் போட்டியுடன் பெரும்பாலான பயிர் சாளரங்களுக்குப் பொருந்தும் குறுகிய கால பயிர்',
    'engine.comp_def_cowpea': 'பல்வேறு மண் மற்றும் பாசன நிலைகளுக்கு ஏற்ற வறட்சியைத் தாங்கும் பயிர்',
    'engine.ir_method_drip': 'முக்கிய மற்றும் ஊடுபயிர் வேர் மண்டலங்களுக்கு இடமாறிய லேட்டரல்களுடன் துடிப்பு சொட்டு இடை-நீர்ப்பாசனம்',
    'engine.ir_method_sprinkler': 'முக்கிய பயிர் மற்றும் ஊடுபயிர் பட்டைகளுக்கு இடையில் மாறும் மண்டல தெளிப்பான் திட்டமிடல்',
    'engine.ir_method_flood': 'ஊடுபயிர் பட்டைகளுக்கு நீர் பரவுவதைக் கட்டுப்படுத்த மாற்று உழவு நீர்ப்பாசனம்',
    'engine.ir_method_manual': 'ஊடுபயிர் பட்டைகளுக்கு கையேடு திசைதிருப்பல் சேனல்களுடன் பேசின் நீர்ப்பாசனம்',
    'engine.ir_method_rainfed': 'தழைக்கூளம் மற்றும் விளிம்பு வரம்புகள் மூலம் ஈரப்பதம் பாதுகாப்பு, உயிர் காக்கும் நீர்ப்பாசனத்துடன் துணைபுரிகிறது',
    'engine.soil_red': 'நீர் தேக்கி வைக்கும் திறனை மேம்படுத்துகிறது மற்றும் கரிம பொருட்கள் குறைந்த செம்மண்ணில் ஓட்டத்தைக் குறைக்கிறது',
    'engine.soil_black': 'கரிசல் மண்ணின் பொதுவான விரிசல் மற்றும் நீர் தேங்குவதை நிர்வகிக்க உதவுகிறது',
    'engine.soil_alluvial': 'ஊட்டச்சத்து சமநிலையை பராமரிக்கிறது மற்றும் மிகவும் வளமான வண்டல் மண்ணில் கசிவைத் தடுக்கிறது',
    'engine.soil_laterite': 'மோசமான நீர் பிடிப்பு திறன் மற்றும் செம்பூறை மண்ணின் அமிலத்தன்மையை எதிர்கொள்கிறது',
    'engine.soil_sandy': 'ஊடுருவல் இழப்புகளைக் குறைக்கிறது மற்றும் மணல் மண்ணில் ஈரப்பதத்தைத் தக்கவைப்பதை மேம்படுத்துகிறது',
    'engine.soil_clay': 'காற்றோட்டத்தை மேம்படுத்துகிறது மற்றும் கனமான களிமண்ணில் நீர் தேங்கும் அழுத்தத்தைத் தடுக்கிறது',
    'engine.soil_def': 'ஒட்டுமொத்த மண்ணின் ஈரப்பதம் பரவலை மேம்படுத்துகிறது மற்றும் பாசன அழுத்தத்தைக் குறைக்கிறது',
    'engine.sched_high': 'பகிரப்பட்ட நீர் பயன்பாட்டை மேம்படுத்த 2-நாள் மாற்று சுழற்சியில் முக்கிய பயிர் மற்றும் ஊடுபயிருக்கு நீர்ப்பாசனம் செய்யுங்கள்',
    'engine.sched_medium': 'கண்காணிக்கப்பட்ட மண்ணின் ஈரப்பதம் சோதனைகளுடன் 4-நாள் மாற்று சுழற்சியில் முக்கிய பயிர் மற்றும் ஊடுபயிருக்கு நீர்ப்பாசனம் செய்யுங்கள்',
    'engine.sched_low': 'முக்கிய பயிர் நீர்ப்பாசனத்திற்கு முன்னுரிமை கொடுங்கள், சேமிக்கப்பட்ட அல்லது எஞ்சிய ஈரப்பதத்துடன் மட்டுமே ஊடுபயிருக்கு துணைபுரியுங்கள்',
    'engine.whatif_base': 'அடிப்படை ஒற்றைப்பயிர் சாகுபடி - பன்முகப்படுத்தல் நன்மைகள் இல்லை',
    'engine.whatif_benefit': '{{stressLess}}% குறைவான நீர் அழுத்த அபாயத்துடன் ₹{{income}} இரண்டாம் நிலை வருமானத்தை சேர்க்கிறது',
    'engine.rec_top_action': '{{crop}} ஐ ஊடுபயிராக {{method}} மூலம் அறிமுகப்படுத்துங்கள்',
    'engine.rec_reasoning': '{{district}} மாவட்டத்தில் {{irrigationType}} நீர்ப்பாசனத்தின் கீழ் {{soilType}} மண்ணில் வளர்க்கப்படும் {{crop}} பயிருக்கு, {{bestPartner}} பயிர் {{synergy}} நீர் ஒத்திசைவை வழங்குகிறது மற்றும் {{comp}}. {{method}} முறையுடன் இணைந்து செயல்படும் போது, இது நீர் பயன்பாட்டை தோராயமாக {{saving}}% குறைக்கும் அதே வேளையில் {{benefit}}.',
    'engine.roi_high': 'ஒரு பருவத்திற்குள் ஏக்கருக்கு 25-35% கூடுதல் வருவாய்',
    'engine.roi_medium': 'ஒரு பருவத்திற்குள் ஏக்கருக்கு 15-25% கூடுதல் வருவாய்',
    'engine.roi_low': 'ஏக்கருக்கு 8-15% கூடுதல் வருவாய், பல பருவங்களில் பெறப்படும்',
    'engine.step_1': '{{crop}} வரிசைகளுடன் {{partner}} பயிருக்கான ஊடுபயிர் பட்டைகளைக் குறிக்கவும், {{depth}} வேர் ஆழத்திற்கான பரிந்துரைக்கப்பட்ட இடைவெளியை பராமரிக்கவும்',
    'engine.step_2': '{{crop}} மற்றும் {{partner}} மண்டலங்கள் இரண்டுக்கும் சேவை செய்ய {{method}} கட்டமைப்பை அமைக்கவும்',
    'engine.step_3': '{{schedule}} முறையைப் பயன்படுத்துங்கள்',
    'engine.step_4': 'முழு {{district}} வயலிலும் ஊடுபயிர் பகுதியை அளவிடுவதற்கு முன் ஒரு பருவத்திற்கு மண்ணின் ஈரப்பதம் மற்றும் மகசூல் பதிலை கண்காணிக்கவும்'
  },
  te: {
    'engine.syn_high': 'అధిక',
    'engine.syn_medium': 'మధ్యస్థ',
    'engine.syn_low': 'తక్కువ',
    'engine.rd_shallow': 'లోతు తక్కువ',
    'engine.rd_medium': 'మధ్యస్థ',
    'engine.rd_deep': 'లోతైన',
    'engine.crop_blackgram': 'మినుము',
    'engine.crop_greengram': 'పెసలు',
    'engine.crop_sesbania': 'జనుము',
    'engine.crop_cowpea': 'అలసంద',
    'engine.crop_onion': 'ఉల్లి',
    'engine.crop_coriander': 'కొత్తిమీర',
    'engine.crop_redgram': 'కంది',
    'engine.crop_castor': 'ఆముదం',
    'engine.crop_sunflower': 'పొద్దుతిరుగుడు',
    'engine.crop_pumpkin': 'గుమ్మడికాయ',
    'engine.comp_paddy_blackgram': 'గట్లపై నత్రజనిని స్థిరపరుస్తుంది, నిలకడ నీటి కోసం పోటీ పడకుండా మిగిలిన తేమతో పెరుగుతుంది',
    'engine.comp_paddy_greengram': 'పొలం అంచులు మరియు కోత తర్వాత నేల తేమను వినియోగించుకునే స్వల్పకాలిక పంట',
    'engine.comp_paddy_sesbania': 'నేల సారాన్ని పెంచే మరియు నీరు నిలిచిపోయే పరిస్థితులను తట్టుకునే పచ్చిరొట్ట ఎరువు పంట',
    'engine.comp_cotton_blackgram': 'లోతు తక్కువ వేర్లు పత్తి తల్లి వేరుతో లోతైన నేల తేమ కోసం పోటీ పడవు',
    'engine.comp_cotton_greengram': 'వేగంగా పెరిగే పప్పుధాన్యపు పంట పత్తి వరుసల మధ్య అమరి నత్రజనిని స్థిరపరుస్తుంది',
    'engine.comp_cotton_cowpea': 'కరువును తట్టుకుంటుంది మరియు పత్తి వరుసల మధ్య నేల ఆకృతిని మెరుగుపరుస్తుంది',
    'engine.comp_sugar_onion': 'చెరకు ఆకులు మూసుకుపోవడానికి ముందు ప్రారంభ దశలో విశాలమైన వరుసల ఖాళీని లోతు తక్కువ గడ్డ పంట వాడుకుంటుంది',
    'engine.comp_sugar_coriander': 'చెరకు స్థాపన దశలో ముందస్తు ఆదాయాన్ని ఇచ్చే స్వల్పకాలిక పంట',
    'engine.comp_sugar_blackgram': 'సుదీర్ఘ చెరకు పెరుగుదల చక్రంలో పప్పుధాన్యపు అంతరపంట నేల నత్రజనిని పెంచుతుంది',
    'engine.comp_ground_redgram': 'లోతైన వేర్లు ఉపరితల నేల తేమను పీల్చుకుంటాయి, ఇది వేరుశనగ లోతు తక్కువ వేరు ప్రాంతానికి అనుబంధంగా ఉంటుంది',
    'engine.comp_ground_castor': 'కరువును తట్టుకునే సరిహద్దు పంట గాలి ఒత్తిడిని మరియు వేరుశనగ నీటి నష్టాన్ని తగ్గిస్తుంది',
    'engine.comp_ground_sunflower': 'సమర్థవంతమైన భూమి వినియోగపు పంట వేరుశనగ లాంటి నీటిపారుదల విధానాలను తట్టుకుంటుంది',
    'engine.comp_maize_cowpea': 'పప్పుధాన్యపు పంట మొక్కజొన్న కోసం నత్రజనిని స్థిరపరుస్తుంది మరియు ఆవిరిని తగ్గించే భూకవచాన్ని అందిస్తుంది',
    'engine.comp_maize_blackgram': 'లోతు తక్కువ వేర్ల పప్పుధాన్యపు పంట లోతైన తేమ కోసం పోటీ పడకుండా మొక్కజొన్న వరుసల మధ్య సరిపోతుంది',
    'engine.comp_maize_pumpkin': 'పాకే తీగలు కలుపు మొక్కలను అణిచివేస్తాయి మరియు మొక్కజొన్న పందిరి కింద నేల తేమను కాపాడతాయి',
    'engine.comp_def_blackgram': 'చాలా నీటిపారుదల విధానాలకు సరిపోయే సాధారణ ప్రయోజన పప్పుధాన్యపు అంతరపంట',
    'engine.comp_def_greengram': 'కనిష్ట నీటి పోటీతో చాలా పంట విండోలకు సరిపోయే స్వల్పకాలిక పప్పుధాన్యపు పంట',
    'engine.comp_def_cowpea': 'వివిధ నేల మరియు నీటిపారుదల పరిస్థితులకు అనుకూలించే కరువును తట్టుకునే పప్పుధాన్యపు పంట',
    'engine.ir_method_drip': 'ప్రధాన మరియు అంతరపంట వేరు ప్రాంతాల కోసం ప్రత్యామ్నాయ పక్క గొట్టాలతో పల్స్ డ్రిప్ అంతర-నీటిపారుదల',
    'engine.ir_method_sprinkler': 'ప్రధాన పంట మరియు అంతరపంట పట్టీల మధ్య ప్రత్యామ్నాయంగా జోనల్ స్ప్రింక్లర్ షెడ్యూల్',
    'engine.ir_method_flood': 'అంతరపంట పట్టీలకు నీరు వ్యాపించడాన్ని పరిమితం చేయడానికి ప్రత్యామ్నాయ సాళ్ల కాలువ నీటిపారుదల',
    'engine.ir_method_manual': 'అంతరపంట పట్టీలకు మాన్యువల్ మళ్లింపు కాలువలతో బేసిన్ నీటిపారుదల',
    'engine.ir_method_rainfed': 'మల్చింగ్ మరియు ఆకృతి గట్ల ద్వారా తేమ సంరక్షణ, ప్రాణరక్షక నీటిపారుదలతో భర్తీ చేయబడింది',
    'engine.soil_red': 'సేంద్రియ పదార్థం తక్కువగా ఉండే ఎర్ర నేలల్లో నీటి నిలుపుదలని మెరుగుపరుస్తుంది మరియు ప్రవాహాన్ని తగ్గిస్తుంది',
    'engine.soil_black': 'నల్ల రేగడి నేలల సాధారణ పగుళ్లు మరియు నీరు నిలిచిపోవడాన్ని నిర్వహించడానికి సహాయపడుతుంది',
    'engine.soil_alluvial': 'పోషక సమతుల్యతను కాపాడుతుంది మరియు అత్యంత సారవంతమైన ఒండ్రు నేలల్లో లీచింగ్ను నివారిస్తుంది',
    'engine.soil_laterite': 'పేలవమైన నీటిని పట్టుకునే సామర్థ్యాన్ని మరియు లాటరైట్ నేలల ఆమ్లత్వాన్ని అరికడుతుంది',
    'engine.soil_sandy': 'ఇసుక నేలల్లో చొరబాటు నష్టాలను తగ్గిస్తుంది మరియు తేమ నిలుపుదలని మెరుగుపరుస్తుంది',
    'engine.soil_clay': 'గాలి ప్రసరణను మెరుగుపరుస్తుంది మరియు బరువైన బంకమట్టి నేలల్లో నీరు నిలిచిపోయే ఒత్తిడిని నివారిస్తుంది',
    'engine.soil_def': 'మొత్తం నేల తేమ పంపిణీని మెరుగుపరుస్తుంది మరియు నీటిపారుదల ఒత్తిడిని తగ్గిస్తుంది',
    'engine.sched_high': 'భాగస్వామ్య నీటి వినియోగాన్ని ఆప్టిమైజ్ చేయడానికి ప్రధాన పంట మరియు అంతరపంటకు 2-రోజుల ప్రత్యామ్నాయ చక్రంలో నీరు పెట్టండి',
    'engine.sched_medium': 'పర్యవేక్షించబడిన నేల తేమ తనిఖీలతో 4-రోజుల ప్రత్యామ్నాయ చక్రంలో ప్రధాన పంట మరియు అంతరపంటకు నీరు పెట్టండి',
    'engine.sched_low': 'ప్రధాన పంట నీటిపారుదలకు ప్రాధాన్యత ఇవ్వండి, సంరక్షించబడిన లేదా మిగిలిన తేమతో మాత్రమే అంతరపంటకు భర్తీ చేయండి',
    'engine.whatif_base': 'ప్రాథమిక ఏక పంట విధానం — వైవిధ్యభరిత ప్రయోజనం లేదు',
    'engine.whatif_benefit': '{{stressLess}}% తక్కువ నీటి ఒత్తిడి ప్రమాదంతో ₹{{income}} ద్వితీయ ఆదాయాన్ని జోడిస్తుంది',
    'engine.rec_top_action': '{{crop}} ని అంతరపంటగా {{method}} తో పరిచయం చేయండి',
    'engine.rec_reasoning': '{{district}} జిల్లాలో {{irrigationType}} కింద {{soilType}} నేలలో పెంచే {{crop}} కోసం, {{bestPartner}} {{synergy}} నీటి సమన్వయాన్ని అందిస్తుంది మరియు {{comp}}. {{method}} తో కలిపితే, ఇది నీటి వినియోగాన్ని సుమారు {{saving}}% వరకు తగ్గిస్తుందని భావిస్తున్నారు, అదే సమయంలో {{benefit}}.',
    'engine.roi_high': 'ఒక సీజన్‌లో ఎకరానికి 25–35% అదనపు రాబడి',
    'engine.roi_medium': 'ఒక సీజన్‌లో ఎకరానికి 15–25% అదనపు రాబడి',
    'engine.roi_low': 'ఎకరానికి 8–15% అదనపు రాబడి, బహుళ సీజన్‌లలో లభిస్తుంది',
    'engine.step_1': '{{crop}} వరుసల వెంట {{partner}} కోసం అంతరపంట పట్టీలను గుర్తించండి, {{depth}} వేరు లోతు కోసం సిఫార్సు చేయబడిన అంతరాన్ని నిర్వహించండి',
    'engine.step_2': '{{crop}} మరియు {{partner}} ప్రాంతాలు రెండింటికీ సేవ చేయడానికి {{method}} మౌలిక సదుపాయాలను ఏర్పాటు చేయండి',
    'engine.step_3': '{{schedule}} విధానాన్ని వర్తింపజేయండి',
    'engine.step_4': 'పూర్తి {{district}} పొలంలో అంతరపంట విస్తీర్ణాన్ని పెంచే ముందు ఒక సీజన్ పాటు నేల తేమ మరియు దిగుబడి ప్రతిస్పందనను పర్యవేక్షించండి'
  },
  kn: {
    'engine.syn_high': 'ಹೆಚ್ಚಿನ',
    'engine.syn_medium': 'ಮಧ್ಯಮ',
    'engine.syn_low': 'ಕಡಿಮೆ',
    'engine.rd_shallow': 'ಆಳವಿಲ್ಲದ',
    'engine.rd_medium': 'ಮಧ್ಯಮ',
    'engine.rd_deep': 'ಆಳವಾದ',
    'engine.crop_blackgram': 'ಉದ್ದಿನಬೇಳೆ',
    'engine.crop_greengram': 'ಹೆಸರುಬೇಳೆ',
    'engine.crop_sesbania': 'ಸೆಸ್ಬೇನಿಯಾ',
    'engine.crop_cowpea': 'ಅಲಸಂದೆ',
    'engine.crop_onion': 'ಈರುಳ್ಳಿ',
    'engine.crop_coriander': 'ಕೊತ್ತಂಬರಿ',
    'engine.crop_redgram': 'ತೊಗರಿಬೇಳೆ',
    'engine.crop_castor': 'ಹರಳು',
    'engine.crop_sunflower': 'ಸೂರ್ಯಕಾಂತಿ',
    'engine.crop_pumpkin': 'ಕುಂಬಳಕಾಯಿ',
    'engine.comp_paddy_blackgram': 'ಬದುಗಳಲ್ಲಿ ಸಾರಜನಕವನ್ನು ಸ್ಥಿರಗೊಳಿಸುತ್ತದೆ',
    'engine.comp_paddy_greengram': 'ಕಡಿಮೆ ಅವಧಿಯ ಬೆಳೆ',
    'engine.comp_paddy_sesbania': 'ಹಸಿರೆಲೆ ಗೊಬ್ಬರ ಬೆಳೆ',
    'engine.comp_cotton_blackgram': 'ಹತ್ತಿ ಬೇರಿನೊಂದಿಗೆ ಸ್ಪರ್ಧಿಸುವುದಿಲ್ಲ',
    'engine.comp_cotton_greengram': 'ಸಾರಜನಕವನ್ನು ಒದಗಿಸುತ್ತದೆ',
    'engine.comp_cotton_cowpea': 'ಬರ ಸಹಿಷ್ಣು',
    'engine.comp_sugar_onion': 'ಕಡಿಮೆ ಅವಧಿಯ ಬೆಳೆ',
    'engine.comp_sugar_coriander': 'ಆರಂಭಿಕ ಆದಾಯ',
    'engine.comp_sugar_blackgram': 'ಸಾರಜನಕ ಒದಗಿಸುತ್ತದೆ',
    'engine.comp_ground_redgram': 'ಆಳವಾದ ಬೇರುಗಳು',
    'engine.comp_ground_castor': 'ಬರ ಸಹಿಷ್ಣು ಗಡಿ ಬೆಳೆ',
    'engine.comp_ground_sunflower': 'ಸಮರ್ಥ ಬೆಳೆ',
    'engine.comp_maize_cowpea': 'ಸಾರಜನಕ ಒದಗಿಸುತ್ತದೆ',
    'engine.comp_maize_blackgram': 'ಆಳವಿಲ್ಲದ ಬೇರು',
    'engine.comp_maize_pumpkin': 'ಕಳೆ ನಿಯಂತ್ರಣ',
    'engine.comp_def_blackgram': 'ಸಾಮಾನ್ಯ ಉದ್ದೇಶದ ಬೆಳೆ',
    'engine.comp_def_greengram': 'ಕಡಿಮೆ ಅವಧಿಯ ಬೆಳೆ',
    'engine.comp_def_cowpea': 'ಬರ ಸಹಿಷ್ಣು ಬೆಳೆ',
    'engine.ir_method_drip': 'ಹನಿ ನೀರಾವರಿ',
    'engine.ir_method_sprinkler': 'ತುಂತುರು ನೀರಾವರಿ',
    'engine.ir_method_flood': 'ಪ್ರವಾಹ ನೀರಾವರಿ',
    'engine.ir_method_manual': 'ಕೈಯಿಂದ ನೀರಾವರಿ',
    'engine.ir_method_rainfed': 'ಮಳೆಯಾಶ್ರಿತ',
    'engine.soil_red': 'ಕೆಂಪು ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_black': 'ಕಪ್ಪು ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_alluvial': 'ಮೆಕ್ಕಲು ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_laterite': 'ಲ್ಯಾಟರೈಟ್ ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_sandy': 'ಮರಳು ಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_clay': 'ಜೇಡಿಮಣ್ಣಿಗೆ ಸೂಕ್ತವಾಗಿದೆ',
    'engine.soil_def': 'ಮಣ್ಣಿನ ತೇವಾಂಶವನ್ನು ಸುಧಾರಿಸುತ್ತದೆ',
    'engine.sched_high': '2-ದಿನಗಳ ನೀರಾವರಿ ಚಕ್ರ',
    'engine.sched_medium': '4-ದಿನಗಳ ನೀರಾವರಿ ಚಕ್ರ',
    'engine.sched_low': 'ಮುಖ್ಯ ಬೆಳೆಗೆ ಆದ್ಯತೆ ನೀಡಿ',
    'engine.whatif_base': 'ಮೂಲ ಏಕಬೆಳೆ - ವೈವಿಧ್ಯತೆಯ ಪ್ರಯೋಜನವಿಲ್ಲ',
    'engine.whatif_benefit': '{{stressLess}}% ಕಡಿಮೆ ನೀರಿನ ಒತ್ತಡದೊಂದಿಗೆ ₹{{income}} ಹೆಚ್ಚುವರಿ ಆದಾಯ',
    'engine.rec_top_action': '{{crop}} ಅನ್ನು {{method}} ದೊಂದಿಗೆ ಅಂತರಬೆಳೆಯಾಗಿ ಪರಿಚಯಿಸಿ',
    'engine.rec_reasoning': '{{district}} ಜಿಲ್ಲೆಯ {{soilType}} ಮಣ್ಣಿನಲ್ಲಿ ಬೆಳೆಯುವ {{crop}} ಬೆಳೆಗೆ, {{bestPartner}} {{synergy}} ನೀರಿನ ಸಮನ್ವಯವನ್ನು ಒದಗಿಸುತ್ತದೆ ಮತ್ತು {{comp}}. {{method}} ಜೊತೆಗೆ ಸೇರಿಸಿದಾಗ, ಇದು ನೀರಿನ ಬಳಕೆಯನ್ನು ಸುಮಾರು {{saving}}% ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಮತ್ತು {{benefit}}.',
    'engine.roi_high': 'ಒಂದು ಋತುವಿನಲ್ಲಿ ಪ್ರತಿ ಎಕರೆಗೆ 25-35% ಹೆಚ್ಚುವರಿ ಆದಾಯ',
    'engine.roi_medium': 'ಒಂದು ಋತುವಿನಲ್ಲಿ ಪ್ರತಿ ಎಕರೆಗೆ 15-25% ಹೆಚ್ಚುವರಿ ಆದಾಯ',
    'engine.roi_low': 'ಬಹು ಋತುಗಳಲ್ಲಿ ಪ್ರತಿ ಎಕರೆಗೆ 8-15% ಹೆಚ್ಚುವರಿ ಆದಾಯ',
    'engine.step_1': '{{crop}} ಸಾಲುಗಳ ಉದ್ದಕ್ಕೂ {{partner}} ಗಾಗಿ ಅಂತರಬೆಳೆ ಪಟ್ಟಿಗಳನ್ನು ಗುರುತಿಸಿ, {{depth}} ಬೇರಿನ ಆಳಕ್ಕಾಗಿ ಶಿಫಾರಸು ಮಾಡಿದ ಅಂತರವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ',
    'engine.step_2': '{{crop}} ಮತ್ತು {{partner}} ವಲಯಗಳಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸಲು {{method}} ಮೂಲಸೌಕರ್ಯವನ್ನು ಹೊಂದಿಸಿ',
    'engine.step_3': '{{schedule}} ಅನ್ನು ಅನ್ವಯಿಸಿ',
    'engine.step_4': 'ಸಂಪೂರ್ಣ {{district}} ಜಮೀನಿನಲ್ಲಿ ಅಂತರಬೆಳೆ ಪ್ರದೇಶವನ್ನು ಹೆಚ್ಚಿಸುವ ಮೊದಲು ಒಂದು ಋತುವಿನ ಮಣ್ಣಿನ ತೇವಾಂಶ ಮತ್ತು ಇಳುವರಿಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ'
  },
  ml: {
    'engine.syn_high': 'ഉയർന്ന',
    'engine.syn_medium': 'ഇടത്തരം',
    'engine.syn_low': 'കുറഞ്ഞ',
    'engine.rd_shallow': 'ആഴമില്ലാത്ത',
    'engine.rd_medium': 'ഇടത്തരം',
    'engine.rd_deep': 'ആഴമുള്ള',
    'engine.crop_blackgram': 'ഉഴുന്ന്',
    'engine.crop_greengram': 'ചെറുപയർ',
    'engine.crop_sesbania': 'സെസ്ബേനിയ',
    'engine.crop_cowpea': 'വൻപയർ',
    'engine.crop_onion': 'ഉള്ളി',
    'engine.crop_coriander': 'മല്ലി',
    'engine.crop_redgram': 'തുവര',
    'engine.crop_castor': 'ആവണക്ക്',
    'engine.crop_sunflower': 'സൂര്യകാന്തി',
    'engine.crop_pumpkin': 'മത്തൻ',
    'engine.comp_paddy_blackgram': 'വരമ്പുകളിൽ നൈട്രജൻ നിലനിർത്തുന്നു',
    'engine.comp_paddy_greengram': 'ഹ്രസ്വകാല വിള',
    'engine.comp_paddy_sesbania': 'പച്ചില വളം',
    'engine.comp_cotton_blackgram': 'പരുത്തിയുമായി മത്സരിക്കില്ല',
    'engine.comp_cotton_greengram': 'നൈട്രജൻ നൽകുന്നു',
    'engine.comp_cotton_cowpea': 'വരൾച്ചയെ ചെറുക്കുന്നു',
    'engine.comp_sugar_onion': 'ഹ്രസ്വകാല വിള',
    'engine.comp_sugar_coriander': 'തുടക്കത്തിലുള്ള വരുമാനം',
    'engine.comp_sugar_blackgram': 'നൈട്രജൻ നൽകുന്നു',
    'engine.comp_ground_redgram': 'ആഴമുള്ള വേരുകൾ',
    'engine.comp_ground_castor': 'അതിർത്തി വിള',
    'engine.comp_ground_sunflower': 'കാര്യക്ഷമമായ വിള',
    'engine.comp_maize_cowpea': 'നൈട്രജൻ നൽകുന്നു',
    'engine.comp_maize_blackgram': 'ആഴമില്ലാത്ത വേരുകൾ',
    'engine.comp_maize_pumpkin': 'കള നിയന്ത്രണം',
    'engine.comp_def_blackgram': 'പൊതുവായ ഇടവിള',
    'engine.comp_def_greengram': 'ഹ്രസ്വകാല വിള',
    'engine.comp_def_cowpea': 'വരൾച്ചയെ ചെറുക്കുന്ന വിള',
    'engine.ir_method_drip': 'തുള്ളിനന',
    'engine.ir_method_sprinkler': 'സ്പ്രിംഗ്ലർ',
    'engine.ir_method_flood': 'പ്രളയ ജലസേചനം',
    'engine.ir_method_manual': 'മാനുവൽ ജലസേചനം',
    'engine.ir_method_rainfed': 'മഴയെ ആശ്രയിക്കുന്ന',
    'engine.soil_red': 'ചെമ്മണ്ണിന് അനുയോജ്യം',
    'engine.soil_black': 'കരിമണ്ണിന് അനുയോജ്യം',
    'engine.soil_alluvial': 'എക്കൽ മണ്ണിന് അനുയോജ്യം',
    'engine.soil_laterite': 'വെട്ടുകല്ലിന് അനുയോജ്യം',
    'engine.soil_sandy': 'മണലിന് അനുയോജ്യം',
    'engine.soil_clay': 'കളിമണ്ണിന് അനുയോജ്യം',
    'engine.soil_def': 'മണ്ണിലെ ഈർപ്പം മെച്ചപ്പെടുത്തുന്നു',
    'engine.sched_high': '2-ദിവസത്തെ ജലസേചന ചക്രം',
    'engine.sched_medium': '4-ദിവസത്തെ ജലസേചന ചക്രം',
    'engine.sched_low': 'പ്രധാന വിളയ്ക്ക് മുൻഗണന നൽകുക',
    'engine.whatif_base': 'അടിസ്ഥാന ഒറ്റവിള - വൈവിധ്യവൽക്കരണ ഗുണമില്ല',
    'engine.whatif_benefit': '{{stressLess}}% കുറഞ്ഞ ജല സമ്മർദ്ദത്തോടെ ₹{{income}} അധിക വരുമാനം',
    'engine.rec_top_action': '{{method}} വഴി {{crop}} ഒരു ഇടവിളയായി അവതരിപ്പിക്കുക',
    'engine.rec_reasoning': '{{district}} ജില്ലയിലെ {{soilType}} മണ്ണിൽ വളരുന്ന {{crop}} വിളയ്ക്ക്, {{bestPartner}} {{synergy}} ജല സമന്വയം നൽകുന്നു ഒപ്പം {{comp}}. {{method}} മായി സംയോജിപ്പിക്കുമ്പോൾ, ഇത് ജല ഉപയോഗം ഏകദേശം {{saving}}% കുറയ്ക്കും, അതേസമയം {{benefit}}.',
    'engine.roi_high': 'ഒരു സീസണിൽ ഏക്കറിന് 25-35% അധിക വരുമാനം',
    'engine.roi_medium': 'ഒരു സീസണിൽ ഏക്കറിന് 15-25% അധിക വരുമാനം',
    'engine.roi_low': 'ഏക്കറിന് 8-15% അധിക വരുമാനം, ഒന്നിലധികം സീസണുകളിൽ ലഭ്യമാകും',
    'engine.step_1': '{{crop}} നിരകൾക്കൊപ്പം {{partner}} ന് ഇടവിള പാടുകൾ അടയാളപ്പെടുത്തുക, {{depth}} വേര് ആഴത്തിന് ശുപാർശ ചെയ്യുന്ന അകലം പാലിക്കുക',
    'engine.step_2': '{{crop}}, {{partner}} മേഖലകൾക്കായി {{method}} അടിസ്ഥാന സൗകര്യങ്ങൾ സജ്ജമാക്കുക',
    'engine.step_3': '{{schedule}} പ്രയോഗിക്കുക',
    'engine.step_4': 'മുഴുവൻ {{district}} പാടത്തും ഇടവിള വ്യാപിപ്പിക്കുന്നതിന് മുമ്പ് ഒരു സീസണിലെ മണ്ണിന്റെ ഈർപ്പവും വിളവും നിരീക്ഷിക്കുക'
  },
  ur: {
    'engine.syn_high': 'اعلی',
    'engine.syn_medium': 'درمیانہ',
    'engine.syn_low': 'کم',
    'engine.rd_shallow': 'کم گہرا',
    'engine.rd_medium': 'درمیانہ',
    'engine.rd_deep': 'گہرا',
    'engine.crop_blackgram': 'ماش',
    'engine.crop_greengram': 'مونگ',
    'engine.crop_sesbania': 'سیسبانیا',
    'engine.crop_cowpea': 'لوبیا',
    'engine.crop_onion': 'پیاز',
    'engine.crop_coriander': 'دھنیا',
    'engine.crop_redgram': 'ارہر',
    'engine.crop_castor': 'ارنڈی',
    'engine.crop_sunflower': 'سورج مکھی',
    'engine.crop_pumpkin': 'کدو',
    'engine.comp_paddy_blackgram': 'نائٹروجن فراہم کرتا ہے',
    'engine.comp_paddy_greengram': 'مختصر مدت کی فصل',
    'engine.comp_paddy_sesbania': 'سبز کھاد',
    'engine.comp_cotton_blackgram': 'کپاس کے ساتھ مقابلہ نہیں کرتا',
    'engine.comp_cotton_greengram': 'نائٹروجن فراہم کرتا ہے',
    'engine.comp_cotton_cowpea': 'خشک سالی برداشت کرنے والا',
    'engine.comp_sugar_onion': 'مختصر مدت کی فصل',
    'engine.comp_sugar_coriander': 'ابتدائی آمدنی',
    'engine.comp_sugar_blackgram': 'نائٹروجن فراہم کرتا ہے',
    'engine.comp_ground_redgram': 'گہری جڑیں',
    'engine.comp_ground_castor': 'سرحدی فصل',
    'engine.comp_ground_sunflower': 'موثر فصل',
    'engine.comp_maize_cowpea': 'نائٹروجن فراہم کرتا ہے',
    'engine.comp_maize_blackgram': 'کم گہری جڑیں',
    'engine.comp_maize_pumpkin': 'جڑی بوٹیوں کا کنٹرول',
    'engine.comp_def_blackgram': 'عام مقصد کی فصل',
    'engine.comp_def_greengram': 'مختصر مدت کی فصل',
    'engine.comp_def_cowpea': 'خشک سالی برداشت کرنے والی فصل',
    'engine.ir_method_drip': 'قطرہ قطرہ',
    'engine.ir_method_sprinkler': 'فوارہ',
    'engine.ir_method_flood': 'سیلابی آبپاشی',
    'engine.ir_method_manual': 'دستی آبپاشی',
    'engine.ir_method_rainfed': 'بارانی',
    'engine.soil_red': 'سرخ مٹی کے لیے موزوں',
    'engine.soil_black': 'کالی مٹی کے لیے موزوں',
    'engine.soil_alluvial': 'زرخیز مٹی کے لیے موزوں',
    'engine.soil_laterite': 'لیٹرائٹ مٹی کے لیے موزوں',
    'engine.soil_sandy': 'ریتیلی مٹی کے لیے موزوں',
    'engine.soil_clay': 'چکنی مٹی کے لیے موزوں',
    'engine.soil_def': 'مٹی کی نمی کو بہتر بناتا ہے',
    'engine.sched_high': '2 دن کا آبپاشی کا چکر',
    'engine.sched_medium': '4 دن کا آبپاشی کا چکر',
    'engine.sched_low': 'بنیادی فصل کو ترجیح دیں',
    'engine.whatif_base': 'بنیادی واحد فصل - کوئی تنوع کا فائدہ نہیں',
    'engine.whatif_benefit': '{{stressLess}}% کم پانی کے دباؤ کے ساتھ ₹{{income}} اضافی آمدنی',
    'engine.rec_top_action': '{{method}} کے ذریعے {{crop}} کو مخلوط فصل کے طور پر متعارف کرائیں',
    'engine.rec_reasoning': '{{district}} ضلع میں {{soilType}} مٹی پر اگائی جانے والی {{crop}} فصل کے لیے، {{bestPartner}} {{synergy}} پانی کی ہم آہنگی فراہم کرتا ہے اور {{comp}}۔ {{method}} کے ساتھ ملا کر، اس سے پانی کے استعمال میں تقریباً {{saving}}% کمی کی توقع ہے جبکہ {{benefit}}۔',
    'engine.roi_high': 'ایک سیزن میں فی ایکڑ 25-35% اضافی آمدنی',
    'engine.roi_medium': 'ایک سیزن میں فی ایکڑ 15-25% اضافی آمدنی',
    'engine.roi_low': 'متعدد سیزنز میں فی ایکڑ 8-15% اضافی آمدنی',
    'engine.step_1': '{{crop}} قطاروں کے ساتھ {{partner}} کے لیے مخلوط فصل کی پٹیاں نشان زد کریں، {{depth}} جڑ کی گہرائی کے لیے تجویز کردہ فاصلہ برقرار رکھیں',
    'engine.step_2': '{{crop}} اور {{partner}} دونوں علاقوں کی خدمت کے لیے {{method}} انفراسٹرکچر قائم کریں',
    'engine.step_3': '{{schedule}} لاگو کریں',
    'engine.step_4': 'پورے {{district}} کھیت میں مخلوط فصل کا رقبہ بڑھانے سے پہلے ایک سیزن کے لیے مٹی کی نمی اور پیداوار کی نگرانی کریں'
  }
};

const interIrrigationKeys = {
  ta: {
    'intercropping': 'இடுபயிர் வளர்ப்பு',
    'inter_irrigation': 'இடை-நீர்ப்பாசனம்',
    'whatif': 'முன்னறிவிப்பு உருவகப்படுத்துதல்',
    'recommendation': 'பரிந்துரை',
    'implementation_steps': 'செயல்படுத்தும் படிகள்',
    'intercrop_pct': 'இடுபயிர் சதவீதம்'
  },
  te: {
    'intercropping': 'అంతర పంటలు',
    'inter_irrigation': 'అంతర నీటిపారుదల',
    'whatif': 'వాట్-ఇఫ్ సిమ్యులేషన్',
    'recommendation': 'సిఫార్సు',
    'implementation_steps': 'అమలు దశలు',
    'intercrop_pct': 'అంతరపంట శాతం'
  },
  kn: {
    'intercropping': 'ಅಂತರಬೆಳೆ',
    'inter_irrigation': 'ಅಂತರ-ನೀರಾವರಿ',
    'whatif': 'ವಾಟ್-ಇಫ್ ಸಿಮ್ಯುಲೇಶನ್',
    'recommendation': 'ಶಿಫಾರಸು',
    'implementation_steps': 'ಅನುಷ್ಠಾನದ ಹಂತಗಳು',
    'intercrop_pct': 'ಅಂತರಬೆಳೆ ಶೇಕಡಾವಾರು'
  },
  ml: {
    'intercropping': 'ഇടവിള',
    'inter_irrigation': 'ഇന്റർ-ജലസേചനം',
    'whatif': 'വാട്ട്-ഇഫ് സിമുലേഷൻ',
    'recommendation': 'ശുപാർശ',
    'implementation_steps': 'നടപ്പാക്കൽ ഘട്ടങ്ങൾ',
    'intercrop_pct': 'ഇടവിള ശതമാനം'
  },
  ur: {
    'intercropping': 'مخلوط فصلیں',
    'inter_irrigation': 'درمیانی آبپاشی',
    'whatif': 'واٹ اف تخروپن',
    'recommendation': 'سفارش',
    'implementation_steps': 'عمل درآمد کے اقدامات',
    'intercrop_pct': 'مخلوط فصل کا فیصد'
  }
};

Object.entries(engineTranslations).forEach(([lang, map]) => {
  const p = './src/locales/' + lang + '.json';
  if (fs.existsSync(p)) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data.engine) data.engine = {};
    if (!data.inter_irrigation_page) data.inter_irrigation_page = {};
    Object.assign(data.engine, map);
    if(interIrrigationKeys[lang]) Object.assign(data.inter_irrigation_page, interIrrigationKeys[lang]);
    fs.writeFileSync(p, JSON.stringify(data, null, 4));
    console.log('Updated ' + lang + '.json with engine and inter_irrigation_page keys');
  }
});
