const fs = require('fs');

const npkData = {
  ta: {
    'auto.nitrogen_label': 'நைட்ரஜன் (N)',
    'auto.phosphorus_label': 'பாஸ்பரஸ் (P)',
    'auto.potassium_label': 'பொட்டாசியம் (K)',
    'auto.status_deficient': 'குறைபாடு',
    'auto.status_low': 'குறைவு',
    'auto.status_optimal': 'உகந்தது',
    'auto.status_surplus': 'உபரி',
    'auto.desc_nitrogen': 'இலை வளர்ச்சி, குளோரோபில் மற்றும் புரதத் தொகுப்புக்கு அத்தியாவசியமானது.',
    'auto.desc_phosphorus': 'வேர் வளர்ச்சி, பூக்கும் மற்றும் விதை உருவாக்கத்திற்கு முக்கியமானது.',
    'auto.desc_potassium': 'நீர் உறிஞ்சுதல், வறட்சி சகிப்புத்தன்மை மற்றும் நோய் எதிர்ப்பை சீராக்குகிறது.',
    'auto.product_Urea': 'யூரியா',
    'auto.product_DAP': 'டி.ஏ.பி (DAP)',
    'auto.product_MOP': 'எம்.ஓ.பி (MOP)',
    'auto.product_Maintain': 'பராமரிக்கவும்',
    'auto.product_Reduce_Urea': 'யூரியாவை குறைக்கவும்',
    'auto.product_Skip_DAP': 'DAP தவிர்க்கவும்',
    'auto.product_Skip_MOP': 'MOP தவிர்க்கவும்',
    'auto.dose_35_kg/acre': '35 கிலோ/ஏக்கர்',
    'auto.dose_25_kg/acre': '25 கிலோ/ஏக்கர்',
    'auto.dose_50_kg/acre': '50 கிலோ/ஏக்கர்',
    'auto.dose_30_kg/acre': '30 கிலோ/ஏக்கர்',
    'auto.dose_15_kg/acre': '15 கிலோ/ஏக்கர்',
    'auto.dose_—': '—',
    'auto.dose_Cut_by_30%': '30% குறைக்கவும்',
    'auto.timing_At_sowing_+_30_DAS_split': 'விதைக்கும் போது + 30 DAS',
    'auto.timing_At_sowing': 'விதைக்கும் போது',
    'auto.timing_Continue_current_inputs': 'தற்போதைய நடைமுறையை தொடரவும்',
    'auto.timing_Skip_basal_dose': 'அடிப்படை அளவை தவிர்க்கவும்',
    'auto.timing_Apply_as_basal_at_sowing': 'விதைக்கும் போது அடிப்படையாக',
    'auto.timing_Apply_as_basal': 'அடிப்படையாக பயன்படுத்தவும்',
    'auto.timing_No_phosphorus_needed': 'பாஸ்பரஸ் தேவையில்லை',
    'auto.timing_Apply_at_30_DAS': '30 DAS இல் பயன்படுத்தவும்',
    'auto.timing_No_potassium_needed': 'பொட்டாசியம் தேவையில்லை',
    'nutrient_intel.soil_index': 'மண் ஊட்டச்சத்து குறியீடு',
    'nutrient_intel.cost_estimate': 'மதிப்பிடப்பட்ட உரம் செலவு',
    'nutrient_intel.district': 'மாவட்டம்',
    'nutrient_intel.healthy_label': 'ஆரோக்கியமானது',
    'nutrient_intel.moderate_label': 'மிதமானது',
    'nutrient_intel.deficient_label': 'குறைபாடு'
  },
  te: {
    'auto.nitrogen_label': 'నత్రజని (N)',
    'auto.phosphorus_label': 'భాస్వరం (P)',
    'auto.potassium_label': 'పొటాషియం (K)',
    'auto.status_deficient': 'లోపం',
    'auto.status_low': 'తక్కువ',
    'auto.status_optimal': 'అనుకూలమైనది',
    'auto.status_surplus': 'అదనపు',
    'auto.desc_nitrogen': 'ఆకు పెరుగుదల, క్లోరోఫిల్ మరియు ప్రోటీన్ సంశ్లేషణకు అవసరం.',
    'auto.desc_phosphorus': 'మూలాల అభివృద్ధి, పుష్పించడం మరియు విత్తనాల ఏర్పాటుకు కీలకం.',
    'auto.desc_potassium': 'నీటి శోషణ, కరువు సహనం మరియు వ్యాధి నిరోధకతను నియంత్రిస్తుంది.',
    'auto.product_Urea': 'యూరియా',
    'auto.product_DAP': 'DAP',
    'auto.product_MOP': 'MOP',
    'auto.product_Maintain': 'కొనసాగించండి',
    'auto.product_Reduce_Urea': 'యూరియాను తగ్గించండి',
    'auto.product_Skip_DAP': 'DAP నివారించండి',
    'auto.product_Skip_MOP': 'MOP నివారించండి',
    'auto.dose_35_kg/acre': '35 కిలోలు/ఎకరం',
    'auto.dose_25_kg/acre': '25 కిలోలు/ఎకరం',
    'auto.dose_50_kg/acre': '50 కిలోలు/ఎకరం',
    'auto.dose_30_kg/acre': '30 కిలోలు/ఎకరం',
    'auto.dose_15_kg/acre': '15 కిలోలు/ఎకరం',
    'auto.dose_—': '—',
    'auto.dose_Cut_by_30%': '30% తగ్గించండి',
    'auto.timing_At_sowing_+_30_DAS_split': 'విత్తేటప్పుడు + 30 DAS',
    'auto.timing_At_sowing': 'విత్తేటప్పుడు',
    'auto.timing_Continue_current_inputs': 'ప్రస్తుత విధానాన్ని కొనసాగించండి',
    'auto.timing_Skip_basal_dose': 'బేసల్ మోతాదును నివారించండి',
    'auto.timing_Apply_as_basal_at_sowing': 'విత్తేటప్పుడు బేసల్‌గా వాడండి',
    'auto.timing_Apply_as_basal': 'బేసల్‌గా వాడండి',
    'auto.timing_No_phosphorus_needed': 'భాస్వరం అవసరం లేదు',
    'auto.timing_Apply_at_30_DAS': '30 DAS లో వాడండి',
    'auto.timing_No_potassium_needed': 'పొటాషియం అవసరం లేదు',
    'nutrient_intel.soil_index': 'నేల పోషక సూచిక',
    'nutrient_intel.cost_estimate': 'అంచనా వేసిన ఎరువుల ఖర్చు',
    'nutrient_intel.district': 'జిల్లా',
    'nutrient_intel.healthy_label': 'ఆరోగ్యకరమైన',
    'nutrient_intel.moderate_label': 'మధ్యస్థం',
    'nutrient_intel.deficient_label': 'లోపం'
  },
  kn: {
    'auto.nitrogen_label': 'ಸಾರಜನಕ (N)',
    'auto.phosphorus_label': 'ರಂಜಕ (P)',
    'auto.potassium_label': 'ಪೊಟ್ಯಾಸಿಯಮ್ (K)',
    'auto.status_deficient': 'ಕೊರತೆ',
    'auto.status_low': 'ಕಡಿಮೆ',
    'auto.status_optimal': 'ಸೂಕ್ತ',
    'auto.status_surplus': 'ಹೆಚ್ಚುವರಿ',
    'auto.desc_nitrogen': 'ಎಲೆಗಳ ಬೆಳವಣಿಗೆ, ಕ್ಲೋರೊಫಿಲ್ ಮತ್ತು ಪ್ರೋಟೀನ್ ಸಂಶ್ಲೇಷಣೆಗೆ ಅಗತ್ಯ.',
    'auto.desc_phosphorus': 'ಬೇರಿನ ಬೆಳವಣಿಗೆ, ಹೂಬಿಡುವಿಕೆ ಮತ್ತು ಬೀಜ ರಚನೆಗೆ ನಿರ್ಣಾಯಕ.',
    'auto.desc_potassium': 'ನೀರಿನ ಹೀರಿಕೊಳ್ಳುವಿಕೆ, ಬರ ಸಹಿಷ್ಣುತೆ ಮತ್ತು ರೋಗ ನಿರೋಧಕತೆಯನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ.',
    'auto.product_Urea': 'ಯೂರಿಯಾ',
    'auto.product_DAP': 'DAP',
    'auto.product_MOP': 'MOP',
    'auto.product_Maintain': 'ನಿರ್ವಹಿಸಿ',
    'auto.product_Reduce_Urea': 'ಯೂರಿಯಾವನ್ನು ಕಡಿಮೆ ಮಾಡಿ',
    'auto.product_Skip_DAP': 'DAP ತಪ್ಪಿಸಿ',
    'auto.product_Skip_MOP': 'MOP ತಪ್ಪಿಸಿ',
    'auto.dose_35_kg/acre': '35 ಕೆ.ಜಿ/ಎಕರೆ',
    'auto.dose_25_kg/acre': '25 ಕೆ.ಜಿ/ಎಕರೆ',
    'auto.dose_50_kg/acre': '50 ಕೆ.ಜಿ/ಎಕರೆ',
    'auto.dose_30_kg/acre': '30 ಕೆ.ಜಿ/ಎಕರೆ',
    'auto.dose_15_kg/acre': '15 ಕೆ.ಜಿ/ಎಕರೆ',
    'auto.dose_—': '—',
    'auto.dose_Cut_by_30%': '30% ಕಡಿಮೆ ಮಾಡಿ',
    'auto.timing_At_sowing_+_30_DAS_split': 'ಬಿತ್ತನೆ ಸಮಯದಲ್ಲಿ + 30 DAS',
    'auto.timing_At_sowing': 'ಬಿತ್ತನೆ ಸಮಯದಲ್ಲಿ',
    'auto.timing_Continue_current_inputs': 'ಪ್ರಸ್ತುತ ವಿಧಾನವನ್ನು ಮುಂದುವರಿಸಿ',
    'auto.timing_Skip_basal_dose': 'ತಳದ ಡೋಸ್ ತಪ್ಪಿಸಿ',
    'auto.timing_Apply_as_basal_at_sowing': 'ಬಿತ್ತನೆ ಸಮಯದಲ್ಲಿ ತಳವಾಗಿ ಬಳಸಿ',
    'auto.timing_Apply_as_basal': 'ತಳವಾಗಿ ಬಳಸಿ',
    'auto.timing_No_phosphorus_needed': 'ರಂಜಕ ಅಗತ್ಯವಿಲ್ಲ',
    'auto.timing_Apply_at_30_DAS': '30 DAS ನಲ್ಲಿ ಬಳಸಿ',
    'auto.timing_No_potassium_needed': 'ಪೊಟ್ಯಾಸಿಯಮ್ ಅಗತ್ಯವಿಲ್ಲ',
    'nutrient_intel.soil_index': 'ಮಣ್ಣಿನ ಪೋಷಕಾಂಶ ಸೂಚ್ಯಂಕ',
    'nutrient_intel.cost_estimate': 'ಅಂದಾಜು ರಸಗೊಬ್ಬರ ವೆಚ್ಚ',
    'nutrient_intel.district': 'ಜಿಲ್ಲೆ',
    'nutrient_intel.healthy_label': 'ಆರೋಗ್ಯಕರ',
    'nutrient_intel.moderate_label': 'ಮಧ್ಯಮ',
    'nutrient_intel.deficient_label': 'ಕೊರತೆ'
  },
  ml: {
    'auto.nitrogen_label': 'നൈട്രജൻ (N)',
    'auto.phosphorus_label': 'ഫോസ്ഫറസ് (P)',
    'auto.potassium_label': 'പൊട്ടാസ്യം (K)',
    'auto.status_deficient': 'അപര്യാപ്തം',
    'auto.status_low': 'കുറവ്',
    'auto.status_optimal': 'അനുയോജ്യം',
    'auto.status_surplus': 'മിച്ചം',
    'auto.desc_nitrogen': 'ഇലകളുടെ വളർച്ച, ക്ലോറോഫിൽ, പ്രോട്ടീൻ സംശ്ലേഷണം എന്നിവയ്ക്ക് അത്യാവശ്യമാണ്.',
    'auto.desc_phosphorus': 'വേരുകളുടെ വികസനം, പൂവിടൽ, വിത്ത് രൂപീകരണം എന്നിവയ്ക്ക് നിർണായകമാണ്.',
    'auto.desc_potassium': 'ജല ആഗിരണം, വരൾച്ചാ സഹിഷ്ണുത, രോഗപ്രതിരോധം എന്നിവ നിയന്ത്രിക്കുന്നു.',
    'auto.product_Urea': 'യൂറിയ',
    'auto.product_DAP': 'DAP',
    'auto.product_MOP': 'MOP',
    'auto.product_Maintain': 'തുടരുക',
    'auto.product_Reduce_Urea': 'യൂറിയ കുറയ്ക്കുക',
    'auto.product_Skip_DAP': 'DAP ഒഴിവാക്കുക',
    'auto.product_Skip_MOP': 'MOP ഒഴിവാക്കുക',
    'auto.dose_35_kg/acre': '35 കിലോ/ഏക്കർ',
    'auto.dose_25_kg/acre': '25 കിലോ/ഏക്കർ',
    'auto.dose_50_kg/acre': '50 കിലോ/ഏക്കർ',
    'auto.dose_30_kg/acre': '30 കിലോ/ഏക്കർ',
    'auto.dose_15_kg/acre': '15 കിലോ/ഏക്കർ',
    'auto.dose_—': '—',
    'auto.dose_Cut_by_30%': '30% കുറയ്ക്കുക',
    'auto.timing_At_sowing_+_30_DAS_split': 'വിതയ്ക്കുമ്പോൾ + 30 DAS',
    'auto.timing_At_sowing': 'വിതയ്ക്കുമ്പോൾ',
    'auto.timing_Continue_current_inputs': 'നിലവിലെ രീതി തുടരുക',
    'auto.timing_Skip_basal_dose': 'അടിസ്ഥാന ഡോസ് ഒഴിവാക്കുക',
    'auto.timing_Apply_as_basal_at_sowing': 'വിതയ്ക്കുമ്പോൾ അടിസ്ഥാനമായി നൽകുക',
    'auto.timing_Apply_as_basal': 'അടിസ്ഥാനമായി നൽകുക',
    'auto.timing_No_phosphorus_needed': 'ഫോസ്ഫറസ് ആവശ്യമില്ല',
    'auto.timing_Apply_at_30_DAS': '30 DAS ൽ നൽകുക',
    'auto.timing_No_potassium_needed': 'പൊട്ടാസ്യം ആവശ്യമില്ല',
    'nutrient_intel.soil_index': 'മണ്ണ് പോഷക സൂചിക',
    'nutrient_intel.cost_estimate': 'വളം ചെലവ് (കണക്കാക്കിയത്)',
    'nutrient_intel.district': 'ജില്ല',
    'nutrient_intel.healthy_label': 'ആരോഗ്യമുള്ളത്',
    'nutrient_intel.moderate_label': 'ഇടത്തരം',
    'nutrient_intel.deficient_label': 'അപര്യാപ്തം'
  },
  ur: {
    'auto.nitrogen_label': 'نائٹروجن (N)',
    'auto.phosphorus_label': 'فاسفورس (P)',
    'auto.potassium_label': 'پوٹاشیم (K)',
    'auto.status_deficient': 'کمی',
    'auto.status_low': 'کم',
    'auto.status_optimal': 'بہترین',
    'auto.status_surplus': 'اضافی',
    'auto.desc_nitrogen': 'پتوں کی نشوونما، کلوروفیل اور پروٹین کی ترکیب کے لیے ضروری ہے۔',
    'auto.desc_phosphorus': 'جڑوں کی نشوونما، پھول اور بیج بننے کے لیے اہم ہے۔',
    'auto.desc_potassium': 'پانی کے جذب، خشک سالی برداشت اور بیماریوں کے خلاف مزاحمت کو کنٹرول کرتا ہے۔',
    'auto.product_Urea': 'یوریا',
    'auto.product_DAP': 'DAP',
    'auto.product_MOP': 'MOP',
    'auto.product_Maintain': 'برقرار رکھیں',
    'auto.product_Reduce_Urea': 'یوریا کم کریں',
    'auto.product_Skip_DAP': 'DAP چھوڑ دیں',
    'auto.product_Skip_MOP': 'MOP چھوڑ دیں',
    'auto.dose_35_kg/acre': '35 کلو/ایکڑ',
    'auto.dose_25_kg/acre': '25 کلو/ایکڑ',
    'auto.dose_50_kg/acre': '50 کلو/ایکڑ',
    'auto.dose_30_kg/acre': '30 کلو/ایکڑ',
    'auto.dose_15_kg/acre': '15 کلو/ایکڑ',
    'auto.dose_—': '—',
    'auto.dose_Cut_by_30%': '30% کم کریں',
    'auto.timing_At_sowing_+_30_DAS_split': 'بوائی کے وقت + 30 DAS',
    'auto.timing_At_sowing': 'بوائی کے وقت',
    'auto.timing_Continue_current_inputs': 'موجودہ طریقہ جاری رکھیں',
    'auto.timing_Skip_basal_dose': 'بنیادی خوراک چھوڑ دیں',
    'auto.timing_Apply_as_basal_at_sowing': 'بوائی کے وقت بنیادی کے طور پر استعمال کریں',
    'auto.timing_Apply_as_basal': 'بنیادی کے طور پر استعمال کریں',
    'auto.timing_No_phosphorus_needed': 'فاسفورس کی ضرورت نہیں',
    'auto.timing_Apply_at_30_DAS': '30 DAS پر استعمال کریں',
    'auto.timing_No_potassium_needed': 'پوٹاشیم کی ضرورت نہیں',
    'nutrient_intel.soil_index': 'مٹی غذائیت انڈیکس',
    'nutrient_intel.cost_estimate': 'تخمینہ کھاد کی لاگت',
    'nutrient_intel.district': 'ضلع',
    'nutrient_intel.healthy_label': 'صحت مند',
    'nutrient_intel.moderate_label': 'درمیانہ',
    'nutrient_intel.deficient_label': 'کمی'
  }
};

Object.entries(npkData).forEach(([lang, map]) => {
  const p = './src/locales/' + lang + '.json';
  if (fs.existsSync(p)) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (!data.auto) data.auto = {};
    if (!data.nutrient_intel) data.nutrient_intel = {};
    Object.entries(map).forEach(([k, v]) => {
      if (k.startsWith('auto.')) data.auto[k.replace('auto.', '')] = v;
      else if (k.startsWith('nutrient_intel.')) data.nutrient_intel[k.replace('nutrient_intel.', '')] = v;
    });
    fs.writeFileSync(p, JSON.stringify(data, null, 4));
    console.log('Updated ' + lang + '.json with Nutrient Intelligence dynamic translations');
  }
});
